### ISSUE TITLE
vscode-unity-debug not available in vscode extension gallery

### ISSUE THREAD

**Issue by isidorn** [Unity-Technologies/vscode-unity-debug#1]
The steps to install are a bit cumbersome http://forum.unity3d.com/threads/vs-code-unity-debugger-extension-preview.369775/
Why is vscode-unity-debug not published to the vscode gallery - would make the install much easier even though it is still a preview.

**Comment by lukaszunity** [comment]
It will be published to the gallery eventually. We are making the preview build available for those who are willing to go through the manual installation process and test it out before it becomes available on the gallery.
