### ISSUE TITLE
Error when using single-step debug: Unable to open 'GameObjectBindings.gen.cs'

### ISSUE THREAD

**Issue by VDerGoW** [Unity-Technologies/vscode-unity-debug#102]
**Error message:**
+ Unable to open 'GameObjectBindings.gen.cs': File not found (file:///c:/buildslave/unity/build/artifacts/generated/common/runtime/GameObjectBindings.gen.cs).

**Installed extensions:**
+ C# (ms-vscode.csharp)
+ Debugger for Unity (unity.unity-debug)
+ Unity Code Snippets (kleber-swf.unity-code-snippets)

**Environment:**
+ Unity 2017.4.4f1
+ Windows 10 pro x64

**Comment by miniwolf** [comment]
What did you do to get this error message? I need some reproduction steps :)

**Comment by falldeaf** [comment]
I'm getting the same error. For me, when set a stop point, it works fine. But when I try to step into a coroutine, I get this error.

**Comment by VDerGoW** [comment]
I have installed Visual Studio 2017 Community Edition and it works right, and I haven't do any config after installed "Debugger for Unity" and "C#" extension.

Just set a breakpoint at line 10, then click step-into, error occurred when reached any class type.

``` csharp
 1.  using UnityEngine;
 2.  using System.Text;
 3.  
 4.  public class Test : MonoBehaviour
 5.  {
 6.      private void Start()
 7.      {
 8.          // test C# value type, set a breakpoint at line 10
 9.          // no problem when click "Step Into"
10.          int i = 123;    
11.  
12.          // test C# class, error occurred when click "Step Into":
13.          // Unable to open 'StringBuilder.cs': File not found 
14.          // (file:///Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Text/StringBuilder.cs).
15.          // StringBuilder sb = new StringBuilder();  // error!!!
16.          // sb.Append("abc");
17.  
18.          // test Unity class, error occurred when click "Step Into":
19.          // Unable to open 'GameObjectBindings.gen.cs': File not found 
20.          // (file:///c:/buildslave/unity/build/artifacts/generated/common/runtime/GameObjectBindings.gen.cs).
21.          GameObject go = new GameObject(); // error!!!
22.          Transform trans = gameObject.GetComponent<Transform>(); // error!!!
23.      }
24.  }
```

**Comment by miniwolf** [comment]
This seem to be a similar problem to this: https://github.com/Unity-Technologies/vscode-unity-debug/issues/74
This must be on the old runtime 3.5?
