### ISSUE TITLE
No define highlighting

### ISSUE THREAD

**Issue by ahuertabhg** [Unity-Technologies/vscode-unity-debug#106]
## Expected Behavior

The editor should highlight code that is defined out differently.

## Current Behavior

Code that is defined out, as in Unity is not compiling it, looks like regular code.

## Steps to Reproduce (for bugs)

1. Open project
2. Open a file with some define dependent code, such as UNITY_ANDROID

## Context

We have code that is platform specific and as such is wrapped in `#if`s dependent on platform. Some areas are complex and are difficult to determine what is being used for what platform because it all looks the same. Visual Studio highlights defined out code correctly.

## Your Environment
* Unity Version: 2017.3.1f1
* VS Code Version: 1.26
* Version of the debugger tool: 2.6.1
* Operating System and version: Windows 10

**Comment by miniwolf** [comment]
The highlighting of code is not implemented in this debugger. The code highlighting is handled by the omnisharp extension. You can report the issue here: https://github.com/omnisharp

**Comment by miniwolf** [comment]
Well if you want to verify the defines, you should be able to see them in the `.csproj` file.

**Comment by ahuertabhg** [comment]
Great. Thanks! I'll go ahead and close.
