### ISSUE TITLE
Please publish latest version to Extension Marketplace

### ISSUE THREAD

**Issue by phindle** [Unity-Technologies/vscode-unity-debug#107]
The latest version available from the MarketPlace is 1.3.0.
Please publish most recent version.
(I cloned the repo & attempted to build, but got errors, and I can't spend time trying to figure out what the issue is).

Many thanks.

**Comment by miniwolf** [comment]
You can find the newest release under releases for now. https://github.com/Unity-Technologies/vscode-unity-debug/releases
However it is planned to be released on the marketplace in the following 2-3 weeks.

**Comment by phindle** [comment]
That's great, thank you! Didn't realise there was a released build available here.

**Comment by miniwolf** [comment]
Yeah no worries :)

**Comment by chanon** [comment]
For some reason, I can't install the vsix files, even using the "Extensions: Install from VSIX..." command.

Could you publish the latest version to marketplace?
