### ISSUE TITLE
Multiple breakpoints across multiple files not hitting

### ISSUE THREAD

**Issue by dwilliamson** [Unity-Technologies/vscode-unity-debug#108]
## Expected Behavior
Breakpoints should be hit across multiple files.

## Current Behavior
Breakpoints currently only ever seem to work for one file. If you have two breakpoints in two different files, only one will ever be hit.

## Possible Solution
I believe the problem is here:

https://github.com/Unity-Technologies/vscode-unity-debug/blob/20daa3b616774468c0dcc0981725401acae574b8/UnityDebug/UnityDebugSession.cs#L510-L519

There is one `setBreakpoints` command received for each file that has breakpoints. As there is no filtering on path, any new breakpoint list will end up removing breakpoints set by previous files. I changed `m_Breakpoints` to be a `Dictionary` and everything worked as expected. The original source from Microsoft does something similar:

https://github.com/Microsoft/MIEngine/blob/b1baa7c0732d392f1913b1e48ef0c3c33c2e8e8a/src/OpenDebugAD7/AD7DebugSession.cs#L1525

## Steps to Reproduce (for bugs)
1. Add two breakpoints in two unique files.
2. Attach the debugger.

## Your Environment
* VS Code Version: 1.27.1
* Version of the debugger tool: 2.6.4
* Operating System and version: Linux Debian 9

**Comment by miniwolf** [comment]
Awesome information, thank you! I will get right on fixing this issue and ping you back when I have the new version out.

**Comment by miniwolf** [comment]
Here is the link to the newest version: https://github.com/Unity-Technologies/vscode-unity-debug/releases/download/Version-2.6.6

**Comment by dwilliamson** [comment]
Thanks for such a quick turnaround! I'll be able to test this on Tuesday next week when I'm next on-site.

**Comment by miniwolf** [comment]
Sounds awesome :)

**Comment by miniwolf** [comment]
I will mark it as closed, if you find issues regarding this we can reopen it.

**Comment by dwilliamson** [comment]
Works beautifully! Thank you!

Release link is here: https://github.com/Unity-Technologies/vscode-unity-debug/releases/tag/Version-2.6.6

**Comment by miniwolf** [comment]
Ohh right, thank you :D Glad that it works for you.
