### ISSUE TITLE
Debugging on Linux and VSCode 1.0

### ISSUE THREAD

**Issue by pragmascript** [Unity-Technologies/vscode-unity-debug#11]
Currently debugging on Linux with Visual Studio Code 1.0 does not seem to work.

You can correctly hit breakpoints and step through code but you can't inspect any variables.
Hovering over a variable does not do anything. Adding a variable to the watch window always results in 
> Evaluate request failed (invalid expression).

**Comment by lukaszunity** [comment]
Did it work with previous versions of VS Code? 

You can also check the log file, I think the path on Linux is  ~/.vscode/extensions/Unity.unity-debug-1.0.3/bin/UnityDebug-log.txt . It might contains some additional details about why the evaluation failed.

I will investigate the issue and get back to you.

**Comment by lukaszunity** [comment]
I'm unable to reproduce this issue, could you share a small Unity project where this happens for you and exact repro steps? Also share the log file mentioned above.

**Comment by pragmascript** [comment]
Thank you for your help. It seemed to be an issue with my project configuration and after I deleted the .vscode folder and project files and regenerated them, the debugger is working again.

**Comment by CoenraadS** [comment]
I am having a similar issue, but on Windows, and only for global variables. The unity team asked me for more information in my bug report, I searched for UnityDebug-log.txt however it does not exist in my project. Is there a similar log file available on Windows?
