### ISSUE TITLE
Unity Editor Hangs and Variables or Watch windows don't populate during Unit Tests

### ISSUE THREAD

**Issue by lugehorsam** [Unity-Technologies/vscode-unity-debug#110]
## Expected Behavior

Switch to VSCode and see populated Variables and Watch panes. 

## Current Behavior

Editor hangs on running test without switching to VSCode automatically, and I see the following:
![screen shot 2018-10-11 at 6 20 18 pm](https://user-images.githubusercontent.com/3965481/46837227-7ceab800-cd82-11e8-82dc-5bf8b16f986c.png)

![screen shot 2018-10-11 at 6 20 43 pm](https://user-images.githubusercontent.com/3965481/46837210-647a9d80-cd82-11e8-8acf-0eb402922605.png)

## Steps to Reproduce (for bugs)

1. Run any Unity NUnit test and put a debug breakpoint inside a line in the test.

## Context

This didn't used to happen as of earlier today. Unclear what I did to change situation.

Cannot use debugger to diagnose issues.

## Your Environment
* Unity Version:
2017.4.11
* VS Code Version:
1.28
* Version of the debugger tool:
1.3.0
* Operating System and version:
Max OSX High Sierra

**Comment by miniwolf** [comment]
There is a preview release that you can try. It has a bigger set of fixes. See if that fixes your issue. https://github.com/Unity-Technologies/vscode-unity-debug/releases/download/Version-2.6.6/unity-debug-2.6.6.vsix

Also you can follow the development on this github page and on this forum. https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/

**Comment by lugehorsam** [comment]
Thanks Miniwolf. I will try that now.

**Comment by dbaner1308** [comment]
I was getting the same issue with Unity 2018.2.6f1, VS Code 1.28.1, Windows 10

However the preview release seems to have fixed it.

Thanks

**Comment by miniwolf** [comment]
Sounds awesome @dbaner1308

**Comment by miniwolf** [comment]
No worries :) I am glad that it works for you

**Comment by vvalente87** [comment]
Hi,
@miniwolf,  using last version  2.6.6  with Unity 2018.3.0f2 (tested on Win10 and MacOS Mojave) I notice  that the issue is present again.
With Unity 2018.2.20f1 it works as normal.

I think that there was a regression. Can you verify that?
Thanks.
