### ISSUE TITLE
If debugger gets stuck or crashes cannot unpause unity.

### ISSUE THREAD

**Issue by faldor20** [Unity-Technologies/vscode-unity-debug#120]
## Expected Behavior
Unity Should be able to be unpaused and work to be resumed
## Current Behavior
When the debugger in vscode needs to be stopped for any reason, mosty due to inspecting very large arrays, the unity instance it is debuging will be stuck in a forced pause state which will require the editor to be restarted.

## Possible Solution
perhaps a different method for pausing unity could be implemented, or maybe a button that issues an unpause command to all paused unity instances.

## Steps to Reproduce (for bugs)
1. Start a unity project, press play and begin debugging script in vscode.
2. In the variables window start opening variables until one gets stuck loading.
3. Press the stop debugging button because it is stuck loading a variable .
4. Return to unity and see that it is a forced pause state that cannot be unpaused.
5. No interaction whatsoever can be performed with the editor and so it must be force closed.

## Context
This is kind of a pain becasue should this happen when you have not saved your scene you will loose your progress.

## Your Environment
* Unity version :2018.3.0f2 (Has happened with every version I've used since as long as i can remember)
* VS Code Version:  1.30.2(same as above)
* Version of the debugger tool: 2.6.6 (same again)
* Operating System and version: windows 10 (same again)

This also happens when performing your debugging in the wrong order sometimes. Starting the debugger and then restarting it at the wrong time in relation to the game in the unity editor being started will cause the same issue but i have forgotten the specific behavior that you must perform.

**Comment by miniwolf** [comment]
The specific issue of unity freezing. Even when the debugger is stopped. Is a bug you should file directly with unity.
As it might require changes in unity code base. I will investigate if I am not sending the disconnect signal, though I am not sure if that is the problem.

**Comment by faldor20** [comment]
well how does the debugger manage to totally stop unity in the first place?
