### ISSUE TITLE
Weird "dependencie" backdoor warning (flatmap-stream)

### ISSUE THREAD

**Issue by nj-neer** [Unity-Technologies/vscode-unity-debug#123]
I'm getting an antivirus alert from the package flatmap-stream wich seem to be a dependencie of this extension :

I am getting the following Antivitus alert :
![image](https://user-images.githubusercontent.com/9463585/53502994-849bc680-3aaf-11e9-87b5-f21602c030bc.png)

![image](https://user-images.githubusercontent.com/9463585/53503344-2b806280-3ab0-11e9-8fe3-c487a2598f18.png)

It seem that this package don't actually "exist"

https://www.npmjs.com/package/flatmap-stream 

Is this a false positive or is something weird hapening ?

**Comment by hamish-milne** [comment]
Yeah, the event-stream package was hijacked recently to include a crypto wallet stealer:

https://github.com/dominictarr/event-stream/issues/116

https://github.com/bitpay/copay/issues/9346

Your AV should clean it up for you, but someone here needs to update a dependency to fix it properly.

**Comment by sinbad** [comment]
Same, AV just flagged this in the 2.7.1 update

**Comment by sinbad** [comment]
In fact, why is VSCode even offering a 2.7.1 version when both this repository and the [official extension page](https://marketplace.visualstudio.com/items?itemName=Unity.unity-debug) show only 2.7.0, which doesn't have flatmap-stream? Was it pushed and withdrawn, confusing the update system?

I've tried to delete metadata here but the VSCode extension updater insists there's a 2.7.1 still available, and will update to it (triggering AV again) given half a chance. I've stopped it auto-updating now but this is clearly an issue.

**Comment by miniwolf** [comment]
I have published 2.7.2. Here is the result of VirusTotal. https://www.virustotal.com/#/file-analysis/ODZjOTg0YzkxNDU3NmVkZjJlNzU0NTI0MGY4ZGNjOWI6MTU1MTMwNTI0Mg==
First of all I am so sorry for causing this problem. And second of all thank you all so much for notifying me about this.
I hope this version will not cause any additional issues.

**Comment by LonMcGregor** [comment]
@miniwolf thanks for the quick update. Checking it just now reveals no issues in Windows Defender. 

To anyone else:
It's worth noting that vscode doesn't delete old versions from the disk, I had to manually delete 2.7.1 from the .vscode/extensions folder. It's not really an issue, as the files are never loaded, but just to be safe it's worth taking a second or two to delete it if your anti-virus hasn't done so already.

**Comment by miniwolf** [comment]
@LonMcGregor good point.
The folders can be found here:
Windows: `%USERPROFILE%.vscode\extensions\Unity.unity-debug-x.y.z`
OSX/Linux: `${HOME}/.vscode/extensions/Unity.unity-debug-x.y.z`

**Comment by nj-neer** [comment]
Thanks for the fast fix, i will confirm that everything is ok tommorow
