### ISSUE TITLE
Extension is containing virus!

### ISSUE THREAD

**Issue by oktonion** [Unity-Technologies/vscode-unity-debug#124]
Currently there is a virus detected in extension modules by Kaspersky Antivirus:

> C:\Users\\...\\.vscode\extensions\.unity.unity-debug-2.7.1\node_modules\flatmap-stream\test\data.js;Visual Studio Code;C:\Users\\...\\.vscode\extensions\.unity.unity-debug-2.7.1\node_modules\flatmap-stream\test\data.js;02/27/2019 22:03:59;HEUR:Trojan.Script.Generic

## Your Environment
* VS Code Version: 1.31.1
* Version of the debugger tool: 2.7.1
* Operating System and version: Windows 10

After quick research seems that is some [well known problem](https://github.com/dominictarr/event-stream/issues/116).

**Comment by miniwolf** [comment]
For everyone>
I have published 2.7.2. Here is the result of VirusTotal. https://www.virustotal.com/#/file-analysis/ODZjOTg0YzkxNDU3NmVkZjJlNzU0NTI0MGY4ZGNjOWI6MTU1MTMwNTI0Mg==
First of all I am so sorry for causing this problem. And second of all thank you all so much for notifying me about this.
I hope this version will not cause any additional issues.

**Comment by baroquedub** [comment]
I have 2.7.2 installed but got two Windows Defender threat reports this morning:
C:\Users\...\.vscode\extensions\unity.unity-debug-2.7.1\node_modules\flatmap-stream\index.min.js
C:\Users\...\.vscode\extensions\unity.unity-debug-2.7.1\node_modules\flatmap-stream\test\data.js

both Trojan:JS/CoinMiner
![vscode-trojan](https://user-images.githubusercontent.com/316458/57286524-50471680-70ad-11e9-9aab-6e60c19b7b27.png)

**Comment by ypapouin** [comment]
Your report date is 28/02/2019, I think that's an outdated report.

**Comment by baroquedub** [comment]
The original report (not mine) was 28/02/2019. When I went to add a new Issue, this one came up so I added by own report as a reply (thinking it was best to keep it in one place as it appears to be the same issue).
Do you think I should post as a new Issue?

**Comment by miniwolf** [comment]
@baroquedub it looks like you still have the 2.7.1 in your extension folder. My suggestion, would be to try deleting the extension. Then go to `%USERPROFILE%/.vscode/extensions/` make sure that the folder is installed. Then install the extension again. This should fix the problem for you.

**Comment by baroquedub** [comment]
Thanks @miniwolf Version number for the extension shows up as 2.7.2 in VSCode but maybe it doesn't clean up after itself on updates. I'll do as you say. delete the whole thing then reinstall. Thanks.
