### ISSUE TITLE
 Code cannot be intelligently patched

### ISSUE THREAD

**Issue by chenyao6** [Unity-Technologies/vscode-unity-debug#128]
Issue Type: <b>Bug</b>

The prompt content is only C# and there is no prompt for unity members and actions.

Extension version: 2.7.2
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (3.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by miniwolf** [comment]
I am not sure if I understand exactly what issue you are having.
Could you try to clarify?

**Comment by miniwolf** [comment]
Close due to inactivity. If you can provide more information about the problem I will be happy to help you out.
