### ISSUE TITLE
Deleting breakpoints doesn't work in some cases

### ISSUE THREAD

**Issue by RobFireproof** [Unity-Technologies/vscode-unity-debug#14]
We had an issue where deleting breakpoints resulted in the breakpoint still being hit (even though it had disappeared from VS Code).

Changing UnityDebugSession.cs line 248 from
if (bp != null && bp.FileName == path) {
to
if (bp != null && string.Equals(bp.FileName, path, StringComparison.OrdinalIgnoreCase)) {
fixed it for us (for some reason the drive letter was "C" in one and "c" in the other.

Could that get rolled into the next version?

Cheers,
Rob.

**Comment by lukaszunity** [comment]
Thanks for the patch, this can definitely be rolled into the next release. I will try to get a new one out as soon as possible.

**Comment by lukaszunity** [comment]
Fixed here https://github.com/Unity-Technologies/vscode-unity-debug/commit/1838890fcff6837921e35d56f7a8d15d7690773d 

Version 1.0.4 with the fix has been published to the VS Code extension gallery.

**Comment by peterthejohnston** [comment]
Just ran into this issue again, running VS Code 1.8.1 on macOS Sierra, with Debugger for Unity v1.1.0.

**Comment by lukaszunity** [comment]
@peterthejohnston, can you share details on how to reproduce this issue?
