### ISSUE TITLE
C# extension dependency error

### ISSUE THREAD

**Issue by cjntaylor** [Unity-Technologies/vscode-unity-debug#153]
## Expected Behavior
The extension loads on startup.

## Current Behavior
The extension fails to load and presents an error message citing the missing extension "ms-vscode.csharp".

## Possible Solution
Update the dependency to use the "ms-dotnettools.csharp" identifier. This may be tricky to work across this boundary, as both identifiers may be in use (depending on the version of the C# extension that is installed).

As a temporary workaround, the updated C# extension (v1.21.13) can be removed, and the v1.21.12 visx can be downloaded from [here](https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.21.12) and installed manually.

## Steps to Reproduce (for bugs)
1. Update the C# to the latest (will happen automatically for most users)
2. Reload the editor

## Context
This issue disables the extension and repeatedly shows the error message when starting vscode. This disables the extension outright.

## Your Environment
* Unity Version: 2019.3.3f1
* VS Code Version: 1.42.1
* Version of the debugger tool: 2.7.2
* Operating System and version: macOS Mojave 10.14.6

**Comment by jcarcamo** [comment]
It also happens on Windows

![image](https://user-images.githubusercontent.com/3542741/76013639-45842a80-5ee6-11ea-9662-9253cf3887d4.png)

**Comment by ChrisWeiss** [comment]
This is addressed in PR #152

**Comment by miniwolf** [comment]
This issue has been fixed and has been pushed live: https://github.com/Unity-Technologies/vscode-unity-debug/pull/152
