### ISSUE TITLE
Unity Version (2019.3.0f6) And VSCode (version 1.4.31) Sometime Cannot Identify Unity Addressable(1.6.2), Compile error!!! not identify namespace about addressable. So I Chose VisualStudio And Then Switch Back To VsCode ,Now Is Can Idnetify

### ISSUE THREAD

**Issue by meichaoge** [Unity-Technologies/vscode-unity-debug#163]
Your issue may already be reported!
![1](https://user-images.githubusercontent.com/17606389/77226742-99189880-6bb5-11ea-9f1a-923e027e2c1b.png)
![12](https://user-images.githubusercontent.com/17606389/77226743-9d44b600-6bb5-11ea-896f-5378059f7b3b.PNG)

Please search on the [issue track](https://github.com/Unity-Technologies/vscode-unity-debug/issues) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
* Unity Version:
* VS Code 

- 

- 

- Versi

1. 

- [ ] 

on:

* Version of the debugger tool:
* Operating System and version:

**Comment by kennelken** [comment]
In my case Unity did not generate file Unity.Addressables.csproj by "Open C# Project". After updating an Addressables package Unity.Addressables.csproj referenced to an old (missing) version.

**Comment by miniwolf** [comment]
This issue is a problem with the `com.unity.ide.vscode` package originating from Unity itself. This extension is for vscode. 
As mentioned by kennelken, you may need to regenerate the csproj files to fix the problem.
