### ISSUE TITLE
Can't set breakpoint on script, Unity not pausing.

### ISSUE THREAD

**Issue by louisspaghetti** [Unity-Technologies/vscode-unity-debug#169]
## Expected Behavior
Select breakpoints in Visual Studio Code to pause Unity at once both the Unity engine and the debugger are running.

## Current Behavior
After selecting breakpoints before or during debugger runtime, Unity does not pause at the selected breakpoints and the following message is given: 
>Could not set breakpoint at location 'c:\Users\Louis de Fromont\Documents\Repos\Unity2D\Glitch Garden\Assets\Scripts\DefenderSpawner.cs:27' (Exception has been thrown by the target of an invocation.)

Full debug log: https://paste.ofcode.org/qtWtrfChQcdzPTf6RPEWNq

## Steps to Reproduce (for bugs)
Setting and breakpoints cause this to happen. Maybe it's dependent on the version?

## Context
I'm not able to set breakpoints and use VSCode to debug.

## Your Environment
* Unity Version: 2019.3.1f1 Personal
* VS Code Version: 1.43.2
* Version of the debugger tool: 2.7.5
* Operating System and version: Windows 10 Home Version 10.0.18362 Build 18362
* VS Code Editor Unity Package Version: 1.2.0

**Comment by miniwolf** [comment]
The reason is due to a bug in VSCode, the current fix is to use Insider version as described in this https://github.com/Unity-Technologies/vscode-unity-debug/issues/166

**Comment by miniwolf** [comment]
If you still have issues we can reopen the bug or create a new.

**Comment by louisspaghetti** [comment]
@miniwolf I just updated VSCode (not the insider version) to version 1.44.0 as specified by the mentioned issue and I'm having the same problem as I had before. I don't think these issues are linked as comparing the behavior shown in #166 with my behavior, they seem quite different and they're issue has no mention of the same errors. 

Their VSCode pauses once they get to the breakpoint while my breakpoint could not even be set (refer to the stated "current behavior"). For this reason, I think this issue should be reopened.

**Comment by miniwolf** [comment]
Ahh I see. Reopening. Unfortunately I cannot see what this exception is.
We will need to debug the debugger to figure that out.

**Comment by louisspaghetti** [comment]
Are there any flags or things I can able so as to provide you more debugging insight?

**Comment by miniwolf** [comment]
The approach right now would be to build the debugger from this repo, following these steps> https://github.com/Unity-Technologies/vscode-unity-debug/wiki/Development-setup
Then while debugging the exception should be hit and then I can see what to solve.

**Comment by miniwolf** [comment]
Better logging is something that I want to improve going forward, but currently we don't have anything

**Comment by miniwolf** [comment]
If you can provide me with a small repro project then I will look into this. I do not see this by a default project.

**Comment by louisspaghetti** [comment]
So to be clear you want me to:
1. Build the extension myself
2. Use the extension that I myself built and start debugging as I normally do
3. Because I built the extension myself you'll know what to solve as soon as I hit the exception?

What difference will it make if I build the extension myself? If I'm just using the same source code to do it, won't it function exactly the same?

**Comment by louisspaghetti** [comment]
Can I just use the prebuilt package found in the releases tab instead of building my own?

**Comment by miniwolf** [comment]
Yes but from the log the only thing I see is: 

> Could not set breakpoint at location 'c:\Users\Louis de Fromont\Documents\Repos\Unity2D\Glitch Garden\Assets\Scripts\DefenderSpawner.cs:27' (Exception has been thrown by the target of an invocation.)

I don't know the exception, the stacktrace or the message from the exception. All I can see is that "something" happened.

If you can use the already built extension, attach the debugger using the source code here, and still get the exception, yes that should also work.

**Comment by louisspaghetti** [comment]
Sorry, I'm not quite sure what you mean by attaching the debugger using the source code here. If I'm using the already built extension under releases (unity-debug-3.0.1.vsix), do I install it in VSCode under the extensions page "Install from VSIX"? I must have misinterpreted what you mean because nothing has changed.

**Comment by miniwolf** [comment]
1. clone the project here.
2. open up the project in Rider or Visual Studio, something that you can use to attach a debugger.
3. attach the extension (the one, already installed) to your unity project. (where you see the problem)
4. Attach the debugger from Rider or Visual Studio, that you opened above, to the UnityDebug application that is running. (Enable stop on exception)
5. Do your repo to hit exception. 

Now you should have a breakpoint in Rider or Visual Studio with the exception message, and a stacktrace that you could share with me

**Comment by louisspaghetti** [comment]
Ok, I think this is that you're looking for:
https://paste.ofcode.org/RY5bXGpL99FtMfhn5TAT6M

**Comment by miniwolf** [comment]
Thank you :) Yes that seems to be right. 
This answer may be what you are looking for: 
https://stackoverflow.com/questions/14509354/this-implementation-is-not-part-of-the-windows-platform-fips-validated-cryptogra

**Comment by louisspaghetti** [comment]
Oh wow! It works absolutely perfect now! Thank you so much for your assistance and sorry for the inconvenience in getting the stack trace.

**Comment by miniwolf** [comment]
Glad we made it work :)
