### ISSUE TITLE
Variable display is difficult to use

### ISSUE THREAD

**Issue by toxikman** [Unity-Technologies/vscode-unity-debug#17]
The variables are displayed in the debugger like {TypeName} {VarName} and in the same color font and it makes it difficult to find a variable that you're looking for. Often the variable name is pushed off the right side of the panel. Is there any way to put the type after the name and in a different color?  Better yet in a different column altogether?

Thanks!

**Comment by lukaszunity** [comment]
How the variables are displayed is completely controlled by VS Code, the debugger extension just returns variable name and value as string data.

You can open this as an issue in the official VS Code repository instead: https://github.com/Microsoft/vscode

**Comment by toxikman** [comment]
Hmm, so you're saying in UnityDebugSession.CreateVariable(), this code:

`var pname = String.Format("{0} {1}", v.TypeName, v.Name);`

...is not used in the variables panel to display the variables?

**Comment by lukaszunity** [comment]
If you look at the full method you can see that the type + name is returned as one value and the value (DisplayValue) is returned another as data to VS Code.

```private Variable CreateVariable(ObjectValue v)
		{
			var pname = String.Format("{0} {1}", v.TypeName, v.Name);
			return new Variable(pname, v.DisplayValue, v.HasChildren ? _variableHandles.Create(v.GetAllChildren()) : 0);
}```

The debugger extension just follows the protocol, it does not specify how the name/value is displayed in VS Code.
