### ISSUE TITLE
Visual Studio code does not recognize rigidbody and other things

### ISSUE THREAD

**Issue by xD4ve** [Unity-Technologies/vscode-unity-debug#172]
Hello, I am David and i have a problem with Visual Studio Code

## Expected Behavior

I watched some Youtube videos but it didnt worked:
https://www.youtube.com/watch?v=qCkFzMSILzk
https://www.youtube.com/watch?v=MawL2dQIZ7s

## Possible Solution

maybe i have the false versions of specific things

## Your Environment
* Unity Version:  Unity 2020.2.0a11.1312.3
* VS Code Version:  VSCode1.47.0
* Version of the debugger tool: 2.7.5
* Operating System and version: Microsoft Windows 10 Home  10.0.18362 Build 18362

**Comment by xD4ve** [comment]
![Image 1](https://user-images.githubusercontent.com/68276206/87413700-ef796f00-c5ca-11ea-9eea-95bec178c75f.jpg)

**Comment by miniwolf** [comment]
In this case the intellisense (hints when you write) are handled by the Omnisharp plugin: https://github.com/OmniSharp/omnisharp-vscode (ms-dotnettools.csharp)

This requires the csproj and sln files generated. These are generated by Unity.
I would verify that these are generated and is correct.

**Comment by xD4ve** [comment]
And how can i do that?

**Comment by xD4ve** [comment]
Update: I made an Windows Update and restarted my Pc and now it seems to work. THANKS A LOT! :D
![Image 1](https://user-images.githubusercontent.com/68276206/87416398-ef7b6e00-c5ce-11ea-8792-2e553cf92977.jpg)

**Comment by miniwolf** [comment]
Great that you got it working :)
