### ISSUE TITLE
Debugger for unity does not break in code called from unity unit tests (2018 only ?)

### ISSUE THREAD

**Issue by OeilDeLance** [Unity-Technologies/vscode-unity-debug#186]
## Expected Behavior
VSCode should be able to break in code called from unity unit tests

## Current Behavior
When setting a breakpoint in code called by the Unity test runner vsCode does break but the call stack crashes and shows  the following "error while processing request ’stack trace’ (exception: this request is not supported by the protocol version implemented by the debugger)". The stack works in the same code when called from a starting a unity scene

## Steps to Reproduce (for bugs)
1. Download the exemple project attached or using https://www.dropbox.com/s/hvx8zyyd8qok83h/CrashingCallStackProject.zip?dl=0
2. Decompress open in unity 2018.4.21
3. Generte vs code solution and open it
4. Put a breakpoint in file NewTestScript line 16
5. Run NewTestScriptSimplePasses

## Context
We are using unit tests to ensure codebase integrity so debugging unit test is super important.

## Your Environment
* Unity Version:2018.4.21f1
* VS Code Version: 1.51.1
* Version of the debugger tool: 3.0.2
* Operating System and version: Win 10 pro 64
[CrashingCallStackProject.zip](https://github.com/Unity-Technologies/vscode-unity-debug/files/5574617/CrashingCallStackProject.zip)

**Comment by OeilDeLance** [comment]
I just realized that this bug is not present when using unity 2019. 
Probably a non issue I guess ^^
We will transition to 2019 anyway so problem solved for us

**Comment by miniwolf** [comment]
Thank you for verifying this on a later version of Unity :) I am sorry that it didn't work in 2018.4. I believe support is ending soon for 2018.4. 2019.4 and 2020.2 will be the LTS versions.
