### ISSUE TITLE
dont auto filling

### ISSUE THREAD

**Issue by Thani0ruvan** [Unity-Technologies/vscode-unity-debug#189]
Issue Type: <b>Bug</b>

i cant use the auto-filling feauture

Extension version: 3.0.2
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A4-4350B R4, 5 COMPUTE CORES 2C+3G      (2 x 2495)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (0.43GB free)|
|Process Argv|E:/unity projects/MyAttempts/Game With 50 feautures -g E:\unity projects\MyAttempts\Game With 50 feautures\Assets\PlayerMovement.cs:1:0 --crash-reporter-id 066772a1-d4fc-4d92-8bcc-70cdb20ecd70|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by miniwolf** [comment]
What auto-filling feature?
Do you mean auto complete, where you type the start of a type and then it will show you the list of known types for you to choose from?

**Comment by Thani0ruvan** [comment]
Thx for quick responce and yes, i mean auto complete. I figure out the
solution anyway. Thx again for quick response
