### ISSUE TITLE
Error on Linux: Unexpected end of input

### ISSUE THREAD

**Issue by idarous** [Unity-Technologies/vscode-unity-debug#19]
Hello,

I'm using Unity3D on Linux. (The version 5.4), Visual studio code 1.5 and the extension debugger for Unity 1.0.4
Note: Unity3d on Linux can be downloaded [here](https://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/) (see the last post).

I follow the instructions described on the README, but after putting a break point and running the project on Unity Editor, I have an error on the debug view of Visual Studio Code: A label appears with the error message "Unexpected end of input".

Does this extension has been tested on Linux ?

**Comment by lukaszunity** [comment]
I have admittedly not tested it myself on Linux, but others have used it with success. I will try to see if I can reproduce it myself. Which version of Linux are you using? And which version of Mono do you have installed on it?

Could you check the log file in ~/.vscode/extensions/Unity.unity-debug-1.0.4/bin and possibly any exceptions the log file?

**Comment by idarous** [comment]
My version of Linux is Linux mint 17.3. I also use mono 4.2.3 and dotnet core version 1.0.0-preview2-003121.

The content of the log file after trying to use the debugger is:

15:29:27.373692: Log
---

15:29:27.380845: UnityDebug
15:29:28.085622: Found Unity process: Unity Editor (Unity) (4064)

**Comment by lukaszunity** [comment]
I've been unable to reproduce this issue with Unity Editor 5.4.0p1 and VS Code 1.5.3 on Ubuntu 14.04 with Mono 3.2.8. I've able to successfully attach to the editor, set breakpoints, step, inspect locals, etc.

**Comment by lukaszunity** [comment]
When I search the web for "Unexpected end of input", I get a lot of hits for JavaScript related issues. 

Since the Unity Debugger extension is written in C# and distributed as an .exe file, I'm leaning towards this being an issue in VS Code and not in the debugger extension. 

The output from your log file also states the the debugger extension is starting correctly and able to find the Unity editor, but then what looks like a Javascript error occurs.

**Comment by idarous** [comment]
The strange. I tested on Ubuntu 16 (on my laptop), it works. But on Linux mint 17.3 (on my desktop), it doesn't work. However, the debugger works for .net core and NodeJS.

**Comment by lukaszunity** [comment]
Does the Mono C# debugger extension work? Unity debugger extension is largely based upon it and shares a great deal of code with it, so I would not be surprised if it had the same issue.

**Comment by idarous** [comment]
I try the [mono C# debugger extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mono-debug.) I can't stop my C# programs even when I put a breakpoint. However, I have this problem with my Ubuntu and my LinuxMint. But on my Ubuntu the unity debug extension works fine. So this is still weird.

Note that I the debugger on the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) works fine on my Ubuntu and my Linux mint.
