### ISSUE TITLE
Warnings in launch.json

### ISSUE THREAD

**Issue by isidorn** [Unity-Technologies/vscode-unity-debug#2]
When generating the initial launch.json VS Code incorrectly thinks it is debug type node and shows warnings. 

I suggest to add the following to your `package.json` `"contributes"` under  `"debuggers"`

`
"configurationAttributes": { "launch": { } }
`

This way vscode will know you register a launch schema. Let me know if you think this is cumbersome

**Comment by lukaszunity** [comment]
Thanks for reporting this issue. I will look into fixing this and also reviewing the package.json file against the specs before the next release.
