### ISSUE TITLE
Multiple targets with name 'Unity Editor' running. Unable to connect on Mac

### ISSUE THREAD

**Issue by azykise** [Unity-Technologies/vscode-unity-debug#20]
can not run debugger , list the console message below:

![qq20161128-0](https://cloud.githubusercontent.com/assets/3301826/20658030/235c1ba2-b575-11e6-8481-87125d8c6667.png)

using Debugger for Unity version 1.1.0
osx version 10.12.1
unity4.7.2f1

hope a fix , thx ...

**Comment by lukaszunity** [comment]
It looks like the process `unityiproxy` is the Unity Remote. Killing the `unityiproxy` process will fix the issue.

https://docs.unity3d.com/460/Documentation/Manual/UnityRemote4.html

You can also work around this issue by using the "Attach to Process Picker" in version 1.10. See the bottom of the README.

We will fix this in upcoming release.

**Comment by lishali12345** [comment]
Attach to Process Picker does not work on macOS, with the error message "command 'attach.attachToDebugger' not found".

These are my development env:
macOS Sierra Version 10.12.2
VS Code Version 1.8.1
Debugger for Unity Version 1.1.0

Error like screenshot below:
![unity_debugger_attach_process_error](https://cloud.githubusercontent.com/assets/170981/21708298/111bf302-d412-11e6-992a-034d6ead67a0.png)

**Comment by lukaszunity** [comment]
@lishali12345 Thanks for reporting this issue. We will look into it.

**Comment by wenjiangtao** [comment]
@lukaszunity I have the same problem with @lishali12345 . Same macOS Version, same VS Code Version, and same problem like screenshot. It says:

command 'attach.attachToDebugger' not found

**Comment by gnshkamath** [comment]
@lukaszunity, any update on "command 'attach.attachToDebugger' not found" issue?

**Comment by lukaszunity** [comment]
I'm unable to reproduce the command 'attach.attachToDebugger' not found issue in a open Unity project which I have the Unity debugger setup for.

**Comment by lukaszunity** [comment]
One thing I'm noticing the screenshot above is that there is no intellisense for any of the C# code, which leads me to believe that Mono is not installed on the system.

The only reason I can see this command failing is if you do not have a system Mono installed, which is also required to run the debugger extension.

Download and install from here: http://www.mono-project.com/download/

**Comment by lukaszunity** [comment]
Original reported issue fixed here: https://github.com/Unity-Technologies/MonoDevelop.Debugger.Soft.Unity/commit/6a561ad4aeddaab4c5ff622d501b9b789c51d394

**Comment by lishali12345** [comment]
@lukaszunity Intellisense for C# code is ok on my MacBook Pro.
