### ISSUE TITLE
Unity Editor crashes when calling function imported with [DllImport (...)]

### ISSUE THREAD

**Issue by andy-fillebrown** [Unity-Technologies/vscode-unity-debug#21]
I'm using the VSCode Unity Debugger on OSX. Everything works fine until I try calling a function in a separate library imported via [DllImport (...)].  My wrapper class looks like this:

`
using System;
using System.Runtime.InteropServices;

namespace csoundcsharp
{
	// This simple wrapper is based on Richard Henninger's Csound6Net .NET wrapper. If you wish to
	// use the Csound API in a model that is idiomatic to .net please use his wrapper instead.
	// http://csound6net.codeplex.com

	// This lightweight wrapper was created to provide an interface to the Unity3d game engine
	public class Csound6
	{
		#if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
       		internal const string _dllVersion = "csound64.dll";
		#elif UNITY_EDITOR_OSX || UNITY_STANDALONE_OSX
			internal const string _dllVersion = "/Assets/StreamingAssets/CsoundLib64.framework/CsoundLib64";
		#endif

		public static class NativeMethods
		{
			[DllImport ("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
			internal static extern bool SetDllDirectory (string lpPathName);

			[DllImport (_dllVersion, CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
			internal static extern Int32 csoundInitialize ([In] int flags);
                }
        }
}
`

...and calling `csound = Csound6.NativeMethods.csoundCreate(IntPtr.Zero);` crashes the Unity Editor. Everything works fine when not debugging in VSCode, and everything works fine when debugging in MonoDevelop, so I'm thinking it's an issue in VSCode?

Any ideas?

**Comment by lukaszunity** [comment]
Can you provide a small Unity project where this happens? Also, the callstack for the crash would be in Unity's Editor.log, which could provide some hints on why it is crashing.

**Comment by andy-fillebrown** [comment]
Thanks, but I'm not seeing a callstack in the log, just some expected Csound init messages, an unexpected "Csound tidy up: Bus error" message, and a Unity thread cleanup warning...

`Csound version 6.07 (double samples) May 16 2016
libsndfile-1.0.21
Csound tidy up: Bus error
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.251s, CPU: 0.002s
***Thread 'UnityLookForNewInputDevices' is still running!***
 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Threads/Thread.cpp Line: 63)

***Thread was not cleaned up!***
 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Threads/Posix/PlatformThread.cpp Line: 38)`

I can provide a small Unity project if necessary, but it will have to include the Csound library and C# wrapper. Is that OK?

**Comment by lukaszunity** [comment]
Sounds a bit odd and like Unity has shut down and not crashed, not sure why. Including everything necessary to reproduce the issue is fine.

**Comment by andy-fillebrown** [comment]
After further investigation this now appears to be a problem with Unity 5.5, not with the VSCode Unity Debugger extension.

Sorry for the noise.

**Comment by matthewlouis** [comment]
Andy - did you ever find a solution to this problem? I'm encountering exact the same thing.

**Comment by andy-fillebrown** [comment]
Sorry, no. I tried rolling back to earlier versions of my code and earlier versions of Unity but the same problem occurred so I figured it was something on the system level causing the issue. I've since switched over to developing on Windows 10. One thing I did notice in my code that may be the cause of the issue is I was setting the system environment in my Unity code to Unity's streaming assets path so Csound's native dynamic library would load. That may have been what was causing Unity's debugging mechanism to fail, but it's just a guess.

Please let me know if you figure out the issue on your end.

Thanks in advance,
~ Andy Fillebrown

**Comment by matthewlouis** [comment]
Thanks, Andy. I tried pretty much everything, and the only thing that works is running it in Windows. It looks like I'm switching over as well.

**Comment by aryamihirsingh** [comment]
Hey guys,
Did any of you find a solution to this? I'm using Windows 8.1 with Unity 5.5.2f1.

**Comment by dps999** [comment]
Hi, it is still crashing on Unity 2017.1. on mac.
