### ISSUE TITLE
Is stepping into DLL's work?

### ISSUE THREAD

**Issue by ajwalters** [Unity-Technologies/vscode-unity-debug#25]
Hello,

I was wondering if stepping into managed DLL's is supported?  We've placed all mdb and pdb files alongside the DLL in the Assets/Plugins directory but we're unable to successfully step into the DLL.    However, we were able to do so successfully via MonoDevelop.

Thanks,
Adam

**Comment by lukaszunity** [comment]
Hi

I know that MonoDevelop has an option for enabling stepping into managed dlls. Sounds like it is disabled by default. I will try to add the option to the debugger extension somehow.

**Comment by augmentedminds** [comment]
We are looking for this as well, would be a great addition. Thanks!

**Comment by ajwalters** [comment]
Can mark this as solved.  I didn't have mono-debug installed as an extension.  Once installed, it all worked as expected
