### ISSUE TITLE
Extension Page Dark Theme

### ISSUE THREAD

**Issue by rakkarage** [Unity-Technologies/vscode-unity-debug#27]
the extension page icon looks great in light but very bad in dark,,,

![2017-03-05 2](https://cloud.githubusercontent.com/assets/962340/23590644/c8ad3f90-01b1-11e7-867d-41f43c172e93.png)

maybe, either
1. change color of icon
2. outline the icon or place on a different color background

thanks

**Comment by rakkarage** [comment]
![2018-05-09 6](https://user-images.githubusercontent.com/962340/39826347-5c786236-5382-11e8-8003-a7969522d220.png)

**Comment by miniwolf** [comment]
@rakkarage yeah, that is just not pretty. I have been keeping this quite low on my fix list. I am rolling out a new release starting next week. I will include this pr as the solution is trivial to incorporate. Thanks for keeping this highlighted

**Comment by rakkarage** [comment]
![0](https://user-images.githubusercontent.com/962340/40594101-fbaddf4e-61fa-11e8-9ab7-e13a33fe7569.jpg)

still shows old image in some places
can replace all three images with one

![0 1](https://user-images.githubusercontent.com/962340/40594108-0358e464-61fb-11e8-8d35-b916eed63c8c.png)

here is a different version made by an ortist with photoshop insteaf of a programmer with gimp and looks a bit better at full size maybe

no prob 
looks great
thanks
