### ISSUE TITLE
Debugger not showing Variables and Watch

### ISSUE THREAD

**Issue by stipe108** [Unity-Technologies/vscode-unity-debug#28]
I was trying out VSCode debugger and encountered some strange behavior. I can successfully attach the debugger to Unity and set breakpoints. My game will pause when it hits the breakpoint and under "Call Stack-Thread 1" it says "Paused on breakpoint". However, it will not highlight the line of code in my editor window, the stacktrace is empty and the Variables and Watched expressions windows are empty.

![screenshot](https://cloud.githubusercontent.com/assets/7650944/23778819/6c26a3ea-04f1-11e7-883f-586c23954dc9.png)

The breakpoint is definitely hit and if I press continue the game runs normally. Placing two breakpoints requires I hit continue twice, as expected. I don't see any other errors in VSCode console, just the normal "Attached to Unity process 'Unity Editor (Unity)' (4094)". I tried debugging with a blank Unity project and it worked, so my setup seems to be correct.

Any ideas as to what could be causing this behavior for my game? Thanks in advance.

Debugger for Unity v1.1.0
VSCode v1.10.2
C# extension v1.7.0
Unity 5.3.6p7

**Comment by lukaszunity** [comment]
I've not seen this before, does debugging work correctly in MonoDevelop for this project?

The best option for getting to the bottom of this is to report a bug and attach the project, so we can reproduce the issue and fix it.

**Comment by stipe108** [comment]
Yes, MonoDevelop debugger works fine. Unfortunately my project is for my company so I can't release any of the code. I also noticed that the VSCode C# extension also doesn't seem to work for my project anymore (no intellisense, jump to declaration, etc). I used VSCode at the end of 2016 and the debugger and the C# extension all worked fine. Not sure what could have happened between then.

Thanks a lot for replying. I will investigate more on my end to see what is wrong with my project.

**Comment by juniordiscart** [comment]
Hi lukaszunity,

I'm on MacOS 10.12.4 with Unity 5.3.4 and encountered this issue many times before as well. In the attachment, I added a simple test project that demonstrates the issue. It seems that breakpoints in the "normal" flow of Awake/Start/Update, breakpoints can be triggered and inspected, but all breakpoints triggering outside that flow (buttons events, network events, other threads) don't allow for inspection.

I hope this can help you in tracking down the issue.
[BreakpointTest.zip](https://github.com/Unity-Technologies/vscode-unity-debug/files/888548/BreakpointTest.zip)

**Comment by bricem** [comment]
Same things here. macOS 10.12.4. VScode 1.11.2. Unity Debugger Plugin 1.1.0. Unity 5.6.0f3.

Debugger is attaching to Unity instance, Unity is paused when the breakpoint is hit but nothing more. VScode can't get focus, and the only thing working is the Stop or Play button which gives the focus back to Unity. 

Worked on older version.

**Comment by Nepoxx** [comment]
I believe this issue should be reopened.
