### ISSUE TITLE
Why is ext not released to the gallery

### ISSUE THREAD

**Issue by SofianHn** [Unity-Technologies/vscode-unity-debug#3]
Any idea why this extension is not released in the gallery? Here is some [docs](https://code.visualstudio.com/docs/tools/vscecli) on how to.

It's also great to see this in VSCode [unity runtime docs](https://code.visualstudio.com/docs/runtimes/unity), docs are [open source](https://github.com/microsoft/vscode-docs) and it will be a great way to give some visibility for this extension if you want help out. 

If you have any issue reach out to me or @chrisdias.

**Comment by lukaszunity** [comment]
As mentioned in issue https://github.com/Unity-Technologies/vscode-unity-debug/issues/1, it will eventually become available in the gallery.
