### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ExoAndy** [Unity-Technologies/vscode-unity-debug#30]
This extension seems to be quite cool and I'd love to use it within the company but unfortunately
I didn't found any license file, not in the repository nor in the Visual Studio Code Marketplace.

Please, add a license file into your repository and to the marketplace!

Thank you very much for your effort and support!

**Comment by lukaszunity** [comment]
Fixed in https://github.com/Unity-Technologies/vscode-unity-debug/commit/e32c66e8b3fdbb87d545829ffb2209a261532409

**Comment by ExoAndy** [comment]
That's awesome! thank you very much!
