### ISSUE TITLE
Debugger not showing instance variables

### ISSUE THREAD

**Issue by gilbertoalexsantos** [Unity-Technologies/vscode-unity-debug#31]
Environment: 
OS: macOS 10.12.3
UnityVersion: 5.5.2f1
VSCode: 1.10.2
VSCode-C#Plugin: 1.8.0
VSCode-DebuggerForUnityVersion: 1.1.0

Issue:
Can't see the value of instance variables (local variables are working fine).

How to reproduce:

1. Create an empty Unity3D project
2. Create a MonoBehaviour class
3. Declare an instance variable 
4. Start Debug and Play Unity
5. Select the variable, right click and select: Debug: Add to Watch
6. It's appearing: Evaluate request failed (invalid expression)

Additional Information:
If you put: 'this.a' instead of 'a' on Debug Console, it'll work.

**Comment by MicBoucinha** [comment]
I can confirm exactly the same situation.

OS: Win 8.0 Enterprise x64
UnityVersion: 5.6.0f3
VSCode; 1.11.1
VSCode-C#Plugin: 1.8.1
VSCode-DebuggerForUnityVersion: 1.1.0

**Comment by Nishok** [comment]
I am having this same issue.

**Comment by lukaszunity** [comment]
Can someone provide an Unity example project where this does not work? Works for me in my test cases.

Do you get any error messages in the VS Code console when evaluation fails?

**Comment by gilbertoalexsantos** [comment]
Seems like the last version (1.2.0) addressed this issue. It's working now.
