### ISSUE TITLE
Stopping the debug adapter on DateTime variable.

### ISSUE THREAD

**Issue by Gravideots** [Unity-Technologies/vscode-unity-debug#33]
**VSCode Version**: 1.12.0;
**Commit**: def9e32;
**Date**: 2017-05-04T16:18:34.633Z;
**Shell**: 1.6.6;
**Renderer**: 56.0.2924.87;
**Node**: 7.4.0;

**OS**: Windows 10; Version:  1607;

**Error from vscode**: Unexpected token { in JSON at position 9. Stopping the debug adapter.

**Errors from Unity console**:

- ToString is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'NewBehaviourScript' on game object 'GameObject'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEngine.Object:ToString()
NewBehaviourScript:.ctor() (at Assets/GameCalendar/Demo/UI/NewBehaviourScript.cs:8)

- get_gameObject is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'NewBehaviourScript' on game object 'GameObject'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEngine.Component:get_gameObject()
NewBehaviourScript:.ctor() (at Assets/GameCalendar/Demo/UI/NewBehaviourScript.cs:8)

- get_transform is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'NewBehaviourScript' on game object 'GameObject'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEngine.Component:get_transform()
NewBehaviourScript:.ctor() (at Assets/GameCalendar/Demo/UI/NewBehaviourScript.cs:8)

**Steps to Reproduce**:

Create new MonoBehaviour script
Put it on scene into any GameObject
Create variable of type System.DateTime
Set breakpoint on created variable
Start debugger
Start PlayMode
Open variable in debugger

![code_2017-05-04_22-20-48](https://cloud.githubusercontent.com/assets/28299743/25721339/bb846bc2-3118-11e7-9d8c-069233fc6fa8.png)

![2017-05-04_22-27-24](https://cloud.githubusercontent.com/assets/28299743/25721369/da3fcc96-3118-11e7-844b-ece75eeed292.png)

**Comment by lukaszunity** [comment]
This is a side-effect of not being allowed to call the Unity API in MonoBehaviour constructors, more details here: 

https://blogs.unity3d.com/2016/06/06/serialization-monobehaviour-constructors-and-unity-5-4/

The debugger evaluates all the members on `this.` and calls the Unity API through properties in the constructor.

**Comment by Gravideots** [comment]
So i guess the only way is stringify Date.
