### ISSUE TITLE
Cannot inspect most complex types during debugging

### ISSUE THREAD

**Issue by strich** [Unity-Technologies/vscode-unity-debug#38]
I thought I'd take a look at the state of the Unity integration with VS Code and unfortunately it appears that there is still some way to go with regards to inspecting variables - It seems that only basic structures are inspectable and I wasn't able to look into the state of most of our more complex objects and classes.

Is this something being actively worked upon?

**Comment by lukaszunity** [comment]
By complex structures, do you mean generic classes?

**Comment by strich** [comment]
Some classes and interfaces. I assumed it was a known thing, but I can go back and provide more exacting detail if you require?

**Comment by lukaszunity** [comment]
There are some objects such a generic containers and generic classes that can only be inspected in a raw view in our current Mono version. These issues will be addressed as part of the ongoing Mono upgrade. 

If you provide some details, then I can tell whether your cases are affect by lack of debugging support in our current Mono runtime.

**Comment by strich** [comment]
Okay so in my case it is simple typed classes stored by interface. It seems like universally interface typed variables are not inspectable.

**Comment by strich** [comment]
Oh FYI I'm on Unity 2017.1b8 and the project is using the experimental .NET upgrade.

**Comment by lukaszunity** [comment]
The debugger has not been tested with the experimental .NET 4.6 upgrade and is not expected to work. We will update the debugger at a later time.

**Comment by strich** [comment]
When might we expect this bug to be resolved Lukas?

**Comment by lukaszunity** [comment]
I hope to find time in the near future to provide a preview build of the debugger extension with .NET 4.6 debugging support.

**Comment by neilsutcliffe** [comment]
I'd really love to see this working. The debug works fine, it just fails once stopping Unity or stopping VSCode debug function. I'm installing Visual Studio now, but much prefer VSCode.

**Comment by miniwolf** [comment]
There is a new preview release which should have fixed this particular issue, if you would like to test it out please visit this post: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/
