### ISSUE TITLE
Closing VS Code during a debug session hard locks Unity v2017.1b8

### ISSUE THREAD

**Issue by strich** [Unity-Technologies/vscode-unity-debug#39]
Using Unity 2017.1b8 and experimental .NET upgrade.

I can repro the case where if I close VS Code during debugging the Unity Editor becomes completely unresponsive. I can also cause this if I properly stop debugging in VS Code using its UI, then try to stop playing in the Editor using the play button.

**Comment by lukaszunity** [comment]
This should be reported as a bug through the Unity bug reporter. We fix this issue in our own fork of the Mono 2.0 runtime and it should also be fixed in the Mono 4.6 runtime.
