### ISSUE TITLE
Could not find target name 'OSX Player'. Is it running?

### ISSUE THREAD

**Issue by jwoodall** [Unity-Technologies/vscode-unity-debug#4]
I tried to set up based on the instructions, but when I hit the green play button  I get "Could not find target name 'OSX Player'. Is it running?"  

Any ideas how to fix?

Running on Mac OSX, VS Code, Unity 5.2.3f, Mono 4.0.1

**Comment by lukaszunity** [comment]
Are you trying to connect to the OSX Player and if so, did you enable development build and script debugging?

**Comment by jwoodall** [comment]
I don't know what the OSX Player is (is that Mono)? I just downloaded your
extension and then removed my current launch script and used yours.

After following your instructions I received that error.

**Comment by lukaszunity** [comment]
You need to select "Unity Editor" to debug Unity. "OSX Player" is for OSX standalone.
