### ISSUE TITLE
Debug Edit Mode unit tests

### ISSUE THREAD

**Issue by dgileadi** [Unity-Technologies/vscode-unity-debug#40]
In VSCode I set a breakpoint in a unit test and started the debugger, which successfully attached to the Unity Editor. Then in Unity I ran my test from the Test Runner's EditMode tab. However the test ran to completion—the process didn't stop at the breakpoint. Am I doing it wrong?

**Comment by lukaszunity** [comment]
This should be working. Can you provide a small Unity project that reproduces this issue?

**Comment by dgileadi** [comment]
Sorry, I was traveling for a week and didn’t get to try this. Then I upgraded to 5.6, reopened my project a few times and to make a long story short debugging Edit Mode tests works now. Sorry for the noise!

-Dave
