### ISSUE TITLE
Debug console truncates strings longer than 100 characters

### ISSUE THREAD

**Issue by greay** [Unity-Technologies/vscode-unity-debug#48]
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:22:50.650Z)
- OS Version: Darwin x64 16.7.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
uncrustify|Lau|2.6.0
unity-debug|Uni|1.2.1
vscode-nuget-package-manager|jmr|1.1.4
cpptools|ms-|0.12.2
csharp|ms-|1.12.0
vscode-icons|rob|7.12.0

---

Steps to Reproduce:

Try to print any string longer than 100 characters in the debug console.
Alternatively, simply input:

"12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890"

which outputs:

"1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890…"

**Comment by GilesDMiddleton** [comment]
Also in Version 1.15.0 - anyone know of a workaround?

**Comment by lukaszunity** [comment]
Not sure if limitation in debugger extension or in VS Code.

**Comment by CWolfs** [comment]
Any movement on this bug?

**Comment by GilesDMiddleton** [comment]
I've just tested debugging .net core, with vscode, and it shows all the characters, but debugging unity limits to 100. I would like to verify the unity extension myself, I downloaded the repo, opened the solution in viscose, are there any instructions for debugging this repo while running unity etc? I've just found the instructions for how to build it, but not how to "debug the extension whilst it's debugging unity" (and I'm on a mac). It's not this MAX_CHILDREN parameter is it?

**Comment by GilesDMiddleton** [comment]
I've found a solution - use Visual Studio community edition - for mac.

**Comment by meds** [comment]
@GilesDMiddleton That is not a solution, that is a really bad work around.

Any progress made on this? It's utterly ridiculous as it stands.

**Comment by whizzkid** [comment]
IT's the reason I'm not using it :(

**Comment by sunflowr** [comment]
Any updates on this? Make's it hard to debug if I can't even see the values.

**Comment by miniwolf** [comment]
There is a new preview release which should have fixed this particular issue, if you would like to test it out please visit this post: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/
