### ISSUE TITLE
Can't set variables like in MonoDevelop

### ISSUE THREAD

**Issue by toxikman** [Unity-Technologies/vscode-unity-debug#49]
While debugging, changing a local variable value causes an error to appear in the watch window: "setVariable not implemented"

The MonoDevelop debugger lets you set variables while debugging, so I assume Unity can support it.

Using "Debugger for Unity" version 1.2.1 and VSCode 0.15.0

**Comment by miniwolf** [comment]
A new preview release that should solve this problem is up here: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/
