### ISSUE TITLE
Could not find target name 'Unity Editor'. Is it running?

### ISSUE THREAD

**Issue by paveldk** [Unity-Technologies/vscode-unity-debug#5]
Nothing fancy - just created a brand new project and added new C# file. Set a break point and tried to debug. The Unity Editor is running.
Got the error:
"Could not find target name 'Unity Editor'. Is it running?"
This is on OSX.
Tried restarting both Unity and VSCode.

http://screencast.com/t/Pn98Q8nol

**Comment by lukaszunity** [comment]
Is "Editor Attaching" enabled in Preferences / External Tools? This option enables script debugging in the editor.

**Comment by paveldk** [comment]
<img width="505" alt="screen shot 2016-01-29 at 8 27 41 am" src="https://cloud.githubusercontent.com/assets/1455045/12668737/5c4affc6-c662-11e5-9ce8-dcdd4e1740ea.png">

**Comment by lukaszunity** [comment]
Could you post the contents of your log file at `~/.vscode/extensions/Unity.unity-debug-1.0.1/bin/UnityDebug-log.txt` ?

**Comment by paveldk** [comment]
08:23:20.335164: Log
---

08:23:20.343363: UnityDebug
08:23:23.898990: Failed to load: PlaybackEngines/iOSSupport/Data/iosdevices.csv
08:23:23.899933: Error while initializing usbmuxd
08:23:23.923815: UnityDebug: Disconnected

**Comment by lukaszunity** [comment]
This is a bit odd, it seems like there no Unity processes are found running on your system. The code for finding the Unity editor is this:

https://github.com/Unity-Technologies/MonoDevelop.Debugger.Soft.Unity/blob/refactor-for-vs-code/UnityProcessDiscovery.cs#L130

Basically is just uses `System.Diagnostics.Process.GetProcesses()` and filters for Unity processes by name. It might be a bug in Mono, which version of Mono do you have installed on your system? You could also check your running processes and see if your Unity is named something else for some reason.

**Comment by paveldk** [comment]
Well I got 2.6.5 (tarball) using the marked as best answer here (http://answers.unity3d.com/questions/259448/how-to-determine-mono-version-of-unity-.html)

And I've got Unity process detected by Activity Monitor.

I'm not sure if the extension is using the same mono as Unity. My "mono --version" is Mono JIT compiler version 3.12.1 (tarball Tue Mar 17 15:03:14 GMT 2015)

Could those be conflicting?

**Comment by lukaszunity** [comment]
Unity bundles it's own version of Mono. VS Code uses the system installed Mono for intellisense and for launching the Unity debugger extension.

I would try to update to the latest Mono (current 4.2.1): http://www.mono-project.com/download/

There might be some issues between the Mono you have installed and your OSX version.

**Comment by paveldk** [comment]
I updated to latest version (4.2.1). Still got the same error, and the error in the log file is the same

**Comment by lukaszunity** [comment]
Download this gist and save it as `Program.cs` 
https://gist.github.com/lukaszunity/3aeb296e8fd5f3c38c8e

Then in a terminal navigate to the directory where you saved then file and type

`mcs Program.cs -out:GetProcesses.exe`
`mono GetProcesses.exe`

This will compile and run a C# program that lists all the processes on your system. Do you see the Unity process in there? Perhaps find the process id in activity monitor and find it that way? And if so, what is the name of it?

My Unity process from the program's output:

> Process ID 20765 Name 'Unity

**Comment by paveldk** [comment]
Well I added some more WriteLines and it seems that Process.GetProcesses() returns 0 running processes.

**Comment by lukaszunity** [comment]
It seems your Mono installation is broken one way or another. I suggest completely removing all Mono installations and re-installing.

Mono is installed at `/Library/Frameworks/Mono.framework/` and you can just completely remove the `Mono.framework` folder. If you have also installed Mono using a package manager or something similar, I would also remove it using those installations. A restart also never hurts ;-)

After you reinstall you should have a `mono` symlinks similar to these.

* `/usr/local/bin/mono -> /Library/Frameworks/Mono.framework/Commands/mono`
* `/Library/Frameworks/Mono.framework/Commands -> /Library/Frameworks/Mono.framework/Versions/Current/bin`
* `/Library/Frameworks/Mono.framework/Versions/Current/bin/mono -> mono-sgen`

If you are still experiencing issues, I suggested filing a Mono bug: https://bugzilla.xamarin.com/

**Comment by paveldk** [comment]
Well @lukaszunity  thank you very much for your time. Your support is much appreciated. 

The problem was indeed in Mono. Apparently the mono I had installed with brew was conflicting with the "official" version which was casing the problem.

So the solution is the one you suggested - remove mono from any package manager and make a clean install from the official website.

Thanks again. Have a great day.
