### ISSUE TITLE
Double clicking compilation errors doesn't go to correct source code line

### ISSUE THREAD

**Issue by GilesDMiddleton** [Unity-Technologies/vscode-unity-debug#52]
VSCode Version 1.15.1 (1.15.1) Mac Sierra 10.12.4
Unity 2017.1.0p5

This has happened for a while now, but when a compilation or exception is raised (where file and line number are available) double clicking the item in the Unity Console opens the correct file, but never the correct line - not even close.

Also seen when running the Unity Integration test runner - Open Error Line does not work either.

**Comment by lukaszunity** [comment]
Thanks for reporting this issue. We will look into it.

**Comment by LitchiSzu** [comment]
It happens to me too. 
Was wondering if someone could tell me if it comes from the extension or from Unity code? Just to know if it's worth looking into it myself :)
Thanks.

**Comment by keithoconor** [comment]
I've been seeing this for a good while too, I thought it was something to do with my setup. Still happens with VSCode 1.19.2 and Unity 2017.3.03f.

**Comment by keithoconor** [comment]
Update: When I went to External Tools in the Preferences dialog, the External Script Editor was showing as "Code.exe". I removed it and then added Code again, and now it shows as "Visual Studio Code" - and it now jumps to the correct line number when double-clicking on an error.

**Comment by fishinsummer04** [comment]
In Unity:
Open Edit->Preference and change the following settings:
External Script Editor Args:-g "$(File):$(Line)"
This fixed for me, I'm using Unity 5, Windows 7.

**Comment by iszlonn** [comment]
> In Unity:
> Open Edit->Preference and change the following settings:
> External Script Editor Args:-g "$(File):$(Line)"
> This fixed for me, I'm using Unity 5, Windows 7.

Thank you, this solved it for me.
Windows 10
Unity 2018.2

**Comment by miniwolf** [comment]
@iszlonn it is curious that it doesn't work for you in 18.2 this bug should be fixed in the latest release of 18.2. The internal argument list is: `$(ProjectPath) -r -g $(file):$(line)`.

**Comment by miniwolf** [comment]
As this is an issue with Unity I will close this bug. If you are experiencing any issues please file a bug with Unity https://unity3d.com/unity/qa/bug-reporting

**Comment by GieziJo** [comment]
>  -r -g $(file):$(line)

For future reference, for people landing here like me, the `F` and `L` should be caps:
`$(ProjectPath) -r -g $(File):$(Line)`

**Comment by miniwolf** [comment]
Right you are @GieziJo

**Comment by m-kul** [comment]
In my case the argument has a semicolon in the beginning, and I tried all of the above arguments with no luck.

> "$(ProjectPath)" -g "$(File)":$(Line):$(Column)
