### ISSUE TITLE
Debugger Hang on when pressing F11

### ISSUE THREAD

**Issue by horney0824** [Unity-Technologies/vscode-unity-debug#53]
I want to press F11 to step in some functions, but yield no response in result with unity instance stuck.  Press F11 on simple value assignment code will produce same result.

VSCode: 1.15.1 32bit
Unity3d: 2017.1.0f3
Debugger for Unity: 1.2.1
VSCode Integration: 2.70-RELEASE

**Comment by lukaszunity** [comment]
Can you provide an piece of example code that causes this issue?

**Comment by horney0824** [comment]
A almost empty project can also produce it. @lukaszunity

**Comment by Nepoxx** [comment]
What does "a almost empty project" mean? Can you provide that?
