### ISSUE TITLE
Can't do debugging: Multiple Targets with the name 'Unity Editor' running

### ISSUE THREAD

**Issue by Everspace** [Unity-Technologies/vscode-unity-debug#58]
I'm currently using `2017.2.f1` Personal (64bit) on Windows 10 Pro (build# 15063.608).

I'm unable to connect to debug the editor due to the following errors:

```
UnityDebug: Initializing
UnityDebug: Searching for Unity process 'Unity Editor'
UnityDebug: Multiple targets with name 'Unity Editor' running. Unable to connect
UnityDebug: Found Unity process 'Unity Editor (Unity)' (4916)
UnityDebug: Found Unity process 'Unity Editor (Unity)' (23776)
UnityDebug: Disconnected
```

There is only 1 visible Unity instance in the taskbar and taskmanager, but opening Process Explorer showed that there were indeed 2 Unitys at it.

![image](https://user-images.githubusercontent.com/7560635/30893176-8bddbd92-a2f1-11e7-8627-d8726dc247f1.png)

The orange column is the pid. The one that is of Explorer seems to be the correct one (23776).

**Comment by lukaszunity** [comment]
Judging by the proccess id 4916, it looks like you have a old Unity process running that was not properly shut down? I don't think this is a bug in the debugger extension.

**Comment by Everspace** [comment]
Odd. When I killed it, Unity crashed. But it seems to no longer persist on the second go-around.

Sorry about that.
