### ISSUE TITLE
Trying to Debug Windows Standalone Build - cannot find target Name

### ISSUE THREAD

**Issue by spaggi2** [Unity-Technologies/vscode-unity-debug#59]
I'm using Version 1.2.1

I built my game with the following settings

![grafik](https://user-images.githubusercontent.com/16560159/30951360-d0318974-a422-11e7-8b27-c9585ad3b37a.png)

Now, I'm selecting "Windows Build" in the Debugger

![grafik](https://user-images.githubusercontent.com/16560159/30951343-b4744d16-a422-11e7-99f3-06cb0c98c956.png)

However I'm getting the following error

![grafik](https://user-images.githubusercontent.com/16560159/30951351-c45d69f6-a422-11e7-9f03-a27b6a0d296c.png)

Am I doing something wrong?

Thank you!

**Comment by lukaszunity** [comment]
Try to enable "Run in background" is in player settings. The player uses a UDP broadcast to let the debugger know that it is running and by enabling "Run in background" the broadcast also happens when the Window does not have focus.

**Comment by spaggi2** [comment]
Hi Lukas,

Thanks a lot for your fast response. I just checked in my project and Run in Background is already active.

You have another idea?

What I also find confusing is that I can’t find anything when typing Unity Attach Debugger in the palette

**Comment by lukaszunity** [comment]
Try to see if you can debug from MonoDevelop. My best guess for why this is happening is because UDP broadcast is being blocked in the player by some software on your computer/

**Comment by spaggi2** [comment]
I can confirm I have the same issue in VS. So it seems not to be related to your Plugin, Thanks a lot!
