### ISSUE TITLE
Coroutines.cs not found error after stepping over yield return statement

### ISSUE THREAD

**Issue by moskal91** [Unity-Technologies/vscode-unity-debug#60]
Unity version: 2017.1.1f1
VS Code version: 1.16.1
Debugger for Unity version: 1.2.1

Error message appears just after stepping over "yield return" statement inside coroutine:
![debug](https://user-images.githubusercontent.com/9036050/31101078-7955e656-a7cc-11e7-96f4-bb7b558d5ec1.gif)

**Comment by moskal91** [comment]
It seems that the same issue affects more users:
https://forum.unity.com/threads/unable-to-open-coroutines-cs-file-not-found.464307/

**Comment by lukaszunity** [comment]
Thanks reporting this and the gif clearly showing the issue :)

**Comment by miniwolf** [comment]
There is a new preview release which should have fixed this particular issue, if you would like to test it out please visit this post: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/
