### ISSUE TITLE
[.NET 4.6] Unity always hangs after stop debugging

### ISSUE THREAD

**Issue by dps999** [Unity-Technologies/vscode-unity-debug#61]
Unity always hangs when i detaching  debugger (stop button).
Unity 2017.1.1f1
VSCode 1.16.1 (1.16.1)
OSx

**Comment by lukaszunity** [comment]
Is this using the .NET 3.5 or .NET 4.6 scripting backend?

**Comment by dps999** [comment]
.Net 4.6

**Comment by lukaszunity** [comment]
The debugger extension is currently not compatible with the .NET 4.6 runtime.

**Comment by blindgoat** [comment]
@lukaszunity Any ETA for when the debugger extension will be compatible with .NET 4.6 runtime?

**Comment by miniwolf** [comment]
I am actively working together with @LukasceUnity to upgrade the .NET 4.6 runtime support. So it will happen soon!

**Comment by neilsutcliffe** [comment]
I'm excited. Let me know if you have something to test :)

**Comment by SirIntruder** [comment]
Great news! 👍

**Comment by miniwolf** [comment]
There is a new preview release which should have fixed this particular issue, if you would like to test it out please visit this post: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/

**Comment by dps999** [comment]
Hi, it works fine, i assume i can close it.
