### ISSUE TITLE
Debugger can't see field value .net 4.6

### ISSUE THREAD

**Issue by dps999** [Unity-Technologies/vscode-unity-debug#62]
Debugger can't see local field value,
but can see local variables of current method and other external public fields from another class.
Also if i create local variable equals this field i can see the value through the local variable.
Could you take a look. Thank you!

![2017-10-06_16-25-20](https://user-images.githubusercontent.com/1697478/31279886-4c6702a8-aab3-11e7-8845-af38f44dc5ba.png)

**Comment by CanisLupus** [comment]
I usually get around this by adding "this." before every object field/property that I want to watch. For static ones use "ClassName."

Nevertheless, this feels unnecessary. The class you're currently in shouldn't require "this.", and perhaps neither "ClassName."

**Comment by miniwolf** [comment]
There is a new preview release which should have fixed this particular issue, if you would like to test it out please visit this post: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/

**Comment by dps999** [comment]
Fixed. Thanks!
