### ISSUE TITLE
Error while trying to view variables

### ISSUE THREAD

**Issue by norpi** [Unity-Technologies/vscode-unity-debug#72]
Unity Debugger Extension - 1.2.1
Visual Studio Code - 1.20.1
Unity - 2017.3.0f3

I turn on the debugger. I launch the scene of Unity. The code fits to breakpoint, stops. I click to view any variable in my code, and following error appears.

![default](https://user-images.githubusercontent.com/18243687/36641445-8fa971fc-1a40-11e8-83d0-b98350c984a8.PNG)

Breakpoint work, but I cant view variables impossible.

**Comment by miniwolf** [comment]
Is this a duplicate of #62 ?
