### ISSUE TITLE
Unable to attach debugger when Unity Hub is open in the background

### ISSUE THREAD

**Issue by benji7425** [Unity-Technologies/vscode-unity-debug#76]
# Summary
When attempting to attach to the Unity Editor with the Unity Hub open in the background, the majority of the time the "Debug adapter process has terminated unexpectedly" error appears. Sometimes it will attach to the editor on the first attempt after opening the Unity project, but not on subsequent attempts.

# Expected behaviour
The debugger attaches to the open Unity Editor

# Actual behaviour
"Debug adapter process has terminated unexpectedly" error

# Steps to reproduce
1. Close any existing instances of the Unity Editor or Unity Hub open
2. Open the Unity Hub
3. Launch a project via the Unity Hub
4. Attempt to attach the debugger
4a. If it worked the first time, stop debugging and try again - it's never worked more than once for me
5. Observe the error

# Workaround
Quitting the Unity Hub from the system tray allows the debugger to be attached as expected

# Environment
Tested on two separate Windows 10 machines, with Unity Editor versions 5.6.1p2 and 2017.1.3f1

**Comment by miniwolf** [comment]
There is a new preview release which should have fixed this particular issue, if you would like to test it out please visit this post: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/

**Comment by benji7425** [comment]
Sorry for the delayed response, this appears to have solved the issue as well as behaving a bit more consistently in general. Thanks for the reply!
