### ISSUE TITLE
Vscode report error about missing UnityEditor.iOS

### ISSUE THREAD

**Issue by byzf** [Unity-Technologies/vscode-unity-debug#77]
Unity Version: 2017.2.0.f3
Reproduction:
1. Create a script
2. Type: "using UnityEditor.iOS"

Vscode report error: The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?) [Assembly-CSharp]

Any workaround?

**Comment by byzf** [comment]
The script works fine under "Asserts/Editor" or "Asserts/XXXX/Editor" directory, but report error under "Asserts/Plugins/Editor" or "Plugins/XXXX/Editor" directory.

Unity Editor doesn't report any error under all above situations, building successfully.

**Comment by miniwolf** [comment]
Is that a problem with this debugger extension? It more sounds like a problem with VScode?
