### ISSUE TITLE
MonoDebug submodule is broken

### ISSUE THREAD

**Issue by K0j0** [Unity-Technologies/vscode-unity-debug#8]
Hello. I cam across this issue trying to build the extension from source. The revision that the MonoDebug submodule points to is broken. My assumption is that it was either deleted or the branch it was on has been rebased. Either way, on a fresh clone of this repo, if one tries to update the submodules they get this error:
` fatal: reference is not a tree: 090c7d93a2d5a64cc6a57abb7338b308025d3949
Unable to checkout '090c7d93a2d5a64cc6a57abb7338b308025d3949' in submodule path 'MonoDebug'`

The link resolves to the correct revision on the github website but there's no branch for it. Instead it says "Tree: 090c7..." which I had never seen before. I assume that github keeps the reference though it's actually lost in a fresh repository.

I'm not sure how important the changes in that orphaned tree are compared to the changes in the add-output-event branch are (that should really get merged into master) but [here they are](https://github.com/Unity-Technologies/vscode-mono-debug/compare/add-output-event...Unity-Technologies:090c7d93a2d5a64cc6a57abb7338b308025d3949).

To be on the safe side I downloaded the orphaned tree as a zip file then copied that into the MonoDebug folder (then updated the sdb submodules) to do a build. I'm not sure if the build would have worked properly if I hadn't done that.

**Comment by lukaszunity** [comment]
Hey

Thanks for reporting this issue. I will fix this by making the submodule point to a revision in our own fork of the vscode-mono-debug repo: https://github.com/Unity-Technologies/vscode-mono-debug

This way we avoid this happening in the future.

**Comment by lukaszunity** [comment]
Should be fixed in 2c811e4950ef85e12db9132ccb1ab5cb6395c22c.
