### ISSUE TITLE
macOS + Unity: unable to keep the current workspace when opening a new file

### ISSUE THREAD

**Issue by bitinn** [Unity-Technologies/vscode-unity-debug#83]
My issue is similar to #67 but the behavior is different.

## Issue

- When VS Code is being used as the default editor, **double-click in Unity to open scripts or shaders will always cause VS Code to reload the Unity project folder as active workspace**.
- It is fine in many cases, but not for my case: I am using a [custom workspace with multiple root folders](https://code.visualstudio.com/docs/editor/multi-root-workspaces).
- For example, my current workspace have 3 root folders: one for *current project*, one for *post processing stack source code*, one for *unity built-in shader source code*.

<img width="266" alt="screen shot 2018-05-22 at 22 13 29" src="https://user-images.githubusercontent.com/1484279/40368045-695d1dc6-5e0d-11e8-9a74-c0f50d4682e9.png">

## Workaround?

1. I opted to use "Open by file extension" instead of "Code" (Unity's built-in VS Code integration I guess?), that allows VS Code to keep active workspace, but I lose the ability to "jump" to a line when double-clicking an Error in Unity's Console.

2. There are some [StackOverflow](https://stackoverflow.com/questions/48824959/vscode-unity-remembering-last-open-session-when-opening-script-form-unity) [answers](https://stackoverflow.com/questions/49550056/unity-opens-multiple-workspaces-when-using-vscode-as-editor/) that suggest using a custom bat script to prevent Unity from knowing too much about VS Code's existence.

3. I think ultimately, we would like to control how Unity invoke VS Code, so these 2 camps:
  - "people who want VS Code to open current project as active workspace"
  - "people who don't want VS Code to open current project, as they use custom workspace"
  - can both be happy.

## Versions

- VS Code: 1.23.1
- Unity: 2018.1
- macOS: 10.13.4
- VSCode Unity Debug Extension: 1.3.0

(PS: would be great to know if we need to use the "preview" 2.x releases)

**Comment by bitinn** [comment]
> so if we could expose this somehow and then you could customize this?

Yeah I think this would be ideal. Many people might like to keep `Directory` in the argument, so I am not suggesting to change the default.

As long as I can set an alternative, it's fine.

**Q: Is this default argument set by Unity Editor, or the Debug extension?**

- If former, then I guess Unity need to update the Editor Preference UI to expose this argument;
- If latter, then I think adding a VS Code extension setting would do.

> However how would one, pass the workspace file through the command line?

We don't need to pass the workspace file though.

If you think about it, anyone using a custom workspace would already have it opened. (because only the user would know which custom workspace he/she wants).

**Comment by miniwolf** [comment]
Absolutely. I will see to making the change in the unity editor. This is where the arguments are passed from.

**Comment by bitinn** [comment]
Additional problem when using "Open by file extension" as workaround instead of "Code":

- I can't use the "compile and show code" for shaders, it returns "Unable to open xxxx.shader: Check external editor in preferences".
- I already have `.shader` and `.hlsl` associate with my VSCode in macOS (double-click works), not sure what else we need here.

**Comment by miniwolf** [comment]
Hmm.. I don't know what should be missing :/ Without the workaround it does work, so I think you may be missing something when removing the arguments passed to VSCode. The arguments being used are `folder -r -g file:line` try that.

**Comment by bitinn** [comment]
Just to clarify, we don’t have access to the user defined argument field in Unity on macOS. Unity should be invoking my default editor for .shader file but perhaps it was a temporary file so it doesn’t work.

Either way I don’t see a fix on my side?

(From my phone)

**Comment by miniwolf** [comment]
When you are doing you custom work around using the bat/batch file, you can actually pass custom arguments from Unity. But it is not a supported thing, though you can do it using these: https://docs.unity3d.com/Manual/Preferences.html under External Script Editor Args

Yeah the fix inside unity is not something that I can just get in. This rewrite goes through a much larger release process. So I will see if I can get it ready for 2018.3, but I am not making any promises.

**Comment by bitinn** [comment]
Thx @miniwolf, I didn't realize `External Script Editor Args` is only available when you set an unknown Editor. Now that I know this, I have figured out how to setup my VSCode properly.

For future visitors:

- Create a `test.sh` file with these lines.

```bash
#!/bin/bash

"/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" "$@"
```

- Now that this handy script, which can create a minimal app from your `test.sh` (this step is needed because Unity on macOS doesn't allow you to select anything other than `.app` as an Editor, unlike Windows.)

https://gist.github.com/mathiasbynens/674099

- After creating your app, make sure it works by trying this in terminal:

`Test.app/Contents/MacOS/Test -r -g /path-to-some-file:10`

- If it works, then you can set it as an external editor in Unity, and set *External Script Editor Args* to:

`-r -g $(File):$(Line)`

- Double-click on scripts and shader in your Unity project and it should work.

That's it, I verify this to work on my macOS 10.13.4 and Unity 2018.1

(I am closing this issue now that I have found a workaround)

**Comment by miniwolf** [comment]
Yes I received that internally as well :) So we are working on it. Thank you.
