### ISSUE TITLE
Debug adapter process has terminated unexpectedly on VScode linux

### ISSUE THREAD

**Issue by AndreArantes** [Unity-Technologies/vscode-unity-debug#84]
I get "Debug adapter process has terminated unexpectedly" when I try to debug Unity 2018.1.0b13 Editor using plugin release 1.3.0 and Visual Studio Code 1.22 on Linux Mint 18.3 Sylvia

<img width="456" alt="38900752-13d4979e-4251-11e8-846d-bfa23a8ed635" src="https://user-images.githubusercontent.com/28788732/40403281-37b4ba08-5e27-11e8-9bd7-16592bc16cf5.png">

No other information is output to the VS Code Debug Console or Output panel.

I only found this version of Unity Debugger extension for VScode. How can I fix it?!

**Comment by miniwolf** [comment]
Could I have you try this preview release listed in this forum post? https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/

**Comment by AndreArantes** [comment]
I tried it, and so, I still get the same problem. I think my VScode isn't recognizing the debugger for some reason :/
I send for you some images which I think can help you help me.
I'm new using VScode and Unity on linux, so I will need some of your attention XD.

![captura de tela de 2018-05-24 11-33-07](https://user-images.githubusercontent.com/28788732/40492293-8d635c28-5f46-11e8-8776-ef51824a03e9.png)
![captura de tela de 2018-05-24 11-30-42](https://user-images.githubusercontent.com/28788732/40492083-1aeff9bc-5f46-11e8-9ed1-dec9332d0ed4.png)
![captura de tela de 2018-05-24 11-24-31](https://user-images.githubusercontent.com/28788732/40492094-2152d694-5f46-11e8-9fe9-226c0eaf0b61.png)
![captura de tela de 2018-05-24 11-24-10](https://user-images.githubusercontent.com/28788732/40492102-2552b73c-5f46-11e8-860a-86218323c988.png)

**Comment by AndreArantes** [comment]
No, I have already installed C# extension
Do you think which this problem can be a incompatibility from .NET on linux?
Because I had some difficulties to install this(.NET) on linux, but the C# extension didn't show any errors after that.
If you have a tutorial showing, step by step, how to install all of this(C# extension, .NET and Unity Debugger) on linux, send me please.

Thanks for you attention!
![captura de tela de 2018-05-24 16-18-34](https://user-images.githubusercontent.com/28788732/40507813-3e65d52e-5f6e-11e8-955c-62cf2cca26d5.png)

**Comment by miniwolf** [comment]
There are a couple of ways to get some logs. First is by going to help > Toggle Developer Console. There may be a stacktrace, or some errors that could help us target this.
In addition, try to do a clean install of this extension, I have experienced that VS Code is not that good at cleaning up after it self. Try uninstall the extension, go to `~/.vscode/extensions` and delete the unity-debug folder complete. Then reinstall and try again.

**Comment by AndreArantes** [comment]
I followed your steps and I still get the same problem.
I took some prints for you, see it and tell me if you found any problem.

![captura de tela de 2018-05-25 09-30-54](https://user-images.githubusercontent.com/28788732/40544550-126d9a2e-5fff-11e8-8c39-4c226342a2b0.png)
![captura de tela de 2018-05-25 09-33-21](https://user-images.githubusercontent.com/28788732/40544549-126d55d2-5fff-11e8-84f1-24b1c41da7cb.png)
![captura de tela de 2018-05-25 09-33-36](https://user-images.githubusercontent.com/28788732/40544563-1feda694-5fff-11e8-8a71-4ad48933b2ab.png)

**Comment by miniwolf** [comment]
@AndreArantes Random question, do you have the Unity Editor open when you are trying to attach?

**Comment by AndreArantes** [comment]
Nope

**Comment by miniwolf** [comment]
Could you try attaching to the Editor when it is started? The debugger will not try to start Unity for you.

**Comment by AndreArantes** [comment]
When you say attach, you mean try to debugger my code? I can't understand, sorry for my noob questions XD

**Comment by miniwolf** [comment]
So when debugging code, you can use an external application, (in this case vscode with this extension), to "attach" to the running code. The code that you want to debug, is running inside of Unity. So what the extension is doing is "attaching" itself to Unity. And gets information about variables, makes it possible to set breakpoints and so on.
In order to be able to do that, Unity needs to be open. Otherwise there is no where for it to attach the debugger.

**Comment by miniwolf** [comment]
What do you mean exactly with "recognise the debugger"? Do you get a new error message?
So does it attach correctly to unity under version 1.3.0 of the tool or what do you mean?

What version of VS Code are you running?

**Comment by AndreArantes** [comment]
I mean recognise the debug type sorry, you can see it on my last  3 prints (the first picture). And the 1.3.0 looks perfectly  attached, but when I try to debbug it does'nt work.
My VScode version is 1.23.1

**Comment by miniwolf** [comment]
Alright. The debug type is just a warning and not related to this issue that you are having.

**Comment by AndreArantes** [comment]
Ah OK, sorry man. So I don't know where is the problem. I think could be something wrong that I'm doing but I can't found it ashahshahsahsh

**Comment by miniwolf** [comment]
I am also trying to get a little frustrated.
In your console developer console, under help, you had a line "Debug adapter process has terminated unexpectedly". Your picture cuts it short, what is on the next lines? That list of blue lines is the stack trace that might give us a clue.

**Comment by miniwolf** [comment]
Also could you check if there is a log file on this path: "~/.vscode/extensions/Unity.unity-debug-2.5.0/UnityDebug-log.txt". Does this contain anything useful?

**Comment by AndreArantes** [comment]
Next of these  blue lines are the same information which I print on the images, the warning triggered two times haha. I tried to debbug again and I took some news prints for you.
Thanks so much for you attention man, It's very important for me.

![captura de tela de 2018-05-25 11-31-31](https://user-images.githubusercontent.com/28788732/40550484-97f1a9ea-6010-11e8-8b3e-9de4bc81a072.png)
![captura de tela de 2018-05-25 11-31-39](https://user-images.githubusercontent.com/28788732/40550485-9811dcec-6010-11e8-9c07-af63b34fc978.png)

**Comment by miniwolf** [comment]
What about this log file that I am referring to?

**Comment by AndreArantes** [comment]
I found it inside UnityDebug-log.txt:

11:58:43.138551: Log
---

11:58:43.148580: UnityDebug

Just it.

**Comment by miniwolf** [comment]
Alright I have enabled some extra logging steps, to try to figure this out. https://files.unity3d.com/nicklas/unity-debug-2.5.0.vsix delete the old extension and install this and give me the output of the log.

**Comment by AndreArantes** [comment]
There is:

13:22:35.706782: Log
---

13:22:35.716087: UnityDebug
13:22:35.716693: Added Logger
13:22:35.716748: Starting Session
13:22:35.719092: Initialize Debug Session

**Comment by AndreArantes** [comment]
Did you find anything?

**Comment by miniwolf** [comment]
Back after weekend. Now we are actually getting somewhere. It stops inside of the Debug Session initializing. Which is very peculiar. Here is a more detailed version that goes into this function so we can see what is going on. Please do the same and give me the output of the log. The new build is here: https://files.unity3d.com/nicklas/unity-debug-2.5.0.vsix

**Comment by miniwolf** [comment]
What version of dotnet do you have? From the terminal: `dotnet --version`

**Comment by miniwolf** [comment]
There we go again, a new build for you to try :D https://files.unity3d.com/nicklas/unity-debug-2.5.0.vsix

**Comment by AndreArantes** [comment]
I will try all of this, and give you a feedback :D

**Comment by miniwolf** [comment]
The last build worked for another user who seemed to have the same problem as you.

**Comment by AndreArantes** [comment]
Well the problem still consisy. My dotnet version is 2.1.4.
And there is UnityDebug-log:
[UnityDebug-log.txt](https://github.com/Unity-Technologies/vscode-unity-debug/files/2045593/UnityDebug-log.txt)

**Comment by miniwolf** [comment]
The log shows some type load failure, it could be that the Mono version is having some issue. What is your mono version?
Also try this version so we may be able to get the information of which type it is trying to load: https://files.unity3d.com/nicklas/unity-debug-2.5.0.vsix

**Comment by AndreArantes** [comment]
**My mono version:** 

Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**And there is the Debug-log:**
[UnityDebug-log.txt](https://github.com/Unity-Technologies/vscode-unity-debug/files/2055327/UnityDebug-log.txt)

**Comment by miniwolf** [comment]
Alright, so could you try upgrading your mono version? I see that 5.12 is out. 4.2.1 is 3 years old now and is probably having some weird issue.

**Comment by AndreArantes** [comment]
Finally it worked, so thanks a lot man. Sorry for my noob questions and whatever that I said haha. You did a great work here, congratulations! :D

**Comment by miniwolf** [comment]
That is soo awesome :D It took too long. But there were multiple things wrong on both ends. But I am soo happy it worked out.

**Comment by miniwolf** [comment]
Hey @heaversm could you open a new bug for this?
As far as I know mono 5.18 is the newest stable version. But I doubt that is the problem.
But if you fill out the information on the issue page maybe something obvious will appear.
