### ISSUE TITLE
"Multiple targets with name 'Unity Editor' running" AND "Evaluate request failed"

### ISSUE THREAD

**Issue by zmicx** [Unity-Technologies/vscode-unity-debug#85]
1 . Debugging with f5, if Multiple UnityEditor opened, this issule occurred. I dont know how to Config the launch.json, so just force terminal one of the Editor, it works.
2. Debugging with breakpoint, then Opening vscode DebugConsole, input a value or express, "Evaluate request failed" occurred.

**Comment by miniwolf** [comment]
1. Under the newest preview release: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/
it will make an estimated guess which project you are trying to attach to. But you still have the option of using the command "Unity Attach Debugger" from the command Pallette.
2. Can you be a bit more specific about which example you are running, just a short reproducible would be very helpful.
In addition, which version are you running, VS Code and extension. What OS is this a problem for you?

**Comment by zmicx** [comment]
Thanks. It seems this issules solved with DebuggerForUnity in version 2.5.0
