### ISSUE TITLE
MacOS Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by miniwolf** [Unity-Technologies/vscode-unity-debug#86]
From AndyBlock:
I'm trying to use 2.5.0 with Unity 5.6.5, macOS 10.13.4 but like joethephish I'm getting "Debug adapter process has terminated unexpectedly" when I try to attach. I already tried this process:

- uninstall extension
- remove .vscode/extensions/Unity.unity-debug*
- install 2.5.0

This has not helped. The log .vscode/extensions/Unity.unity-debug-2.5.0//bin/UnityDebug-log.txt doesn't seem to have anything of interest. I dunno if 2.5.0 was the version your mentioned that "has refactored much of the code and the way it interacts with vscode extension libraries"? Is there something else I can try or more info I can provide you with?

**Comment by andy-block** [comment]
Thanks for getting back about this. I tried the version you linked with debugging enabled (https://files.unity3d.com/nicklas/unity-debug-2.5.0.vsix). Same result, but now there is a little more info in the log file:

```
MacBook-Pro-3:tmh ablock$ less /Users/ablock/.vscode/extensions/Unity.unity-debug-2.5.0/bin/UnityDebug-log.txt
11:05:58.798161: Log
---

11:05:58.810913: UnityDebug
11:05:58.813500: Added Logger
11:05:58.813727: Starting Session
11:05:58.817966: Initialize Debug Session
```

Let me know if I can provide more info / try something else!

**Comment by miniwolf** [comment]
This is really weird, it seems like .NET cannot construct the debugger.
Please try again, I have updated the link with the new file: https://files.unity3d.com/nicklas/unity-debug-2.5.0.vsix

**Comment by miniwolf** [comment]
Which version of dotnet do you run? terminal: `dotnet --version`

**Comment by andy-block** [comment]
Using the updated link, I get the same thing.
 ```
MacBook-Pro-3:tmh ablock$ dotnet --version
2.0.2
```

**Comment by miniwolf** [comment]
Hmm. Could you try upgrading to the newest version? I see that at least 2.1.2 is out?

**Comment by andy-block** [comment]
Yes, that's done it! Awesome, thanks for your help!

**Comment by miniwolf** [comment]
Awesome :D I am really happy we figured this out, this problem has been bugging me for some time.
