### ISSUE TITLE
From the Unity menu Assets/Open C# Project to open the vs code, two vs code projects pop up.

### ISSUE THREAD

**Issue by hubluesky** [Unity-Technologies/vscode-unity-debug#88]
From the Unity menu Assets/Open C# Project to open the vs code, two vs code projects pop up.

**Comment by miniwolf** [comment]
There seems to be a mismatch inside of Unity on how double clicking on a script to open the project and how the menu works. For now as a work around, double clicking the script will get what you need, I think?

**Comment by hubluesky** [comment]
Double click on the script will open two vs code

**Comment by miniwolf** [comment]
Can you give me some information about your system? Version of unity, version of tools? And maybe a small example project with some repro steps?

**Comment by hubluesky** [comment]
## Steps to Reproduce (for bugs)


1.Create an empty project
2.Create C# Script
3.Double click to open this script
4.At this time it is possible to open two vscode
5.If you do not open two vscode，create a C# Script again.
6.Double-click to open any script
7.This will open two vscode

## Context





## Your Environment
* VS Code Version used: 1.23.1
* Version of the debugger tool: 2.5.0
* Operating System and version: win10
* Any additional information you think could help

**Comment by miniwolf** [comment]
What version of Unity are you using?

**Comment by hubluesky** [comment]
unity version: 5.6.2f1

**Comment by miniwolf** [comment]
I tried this on 5.6.2f1 and 5.6.5f1, and I cannot reproduce this problem.

**Comment by SirIntruder** [comment]
It doesn't really matter which Unity version it is, it is happening on both 2017 and 2018.
Repro 100% for me is 1.) open c# project, 2.) close 3.) open c# project again, it will be doubled, and will continue opening double from now on

**Comment by miniwolf** [comment]
Okay maybe I am misunderstanding this. But are we talking about double clicking a script and it will open two vs code windows, or are we talking about using the Assets/Open C# project from the menu?
Because the open c# project from the menu is broken, and is a problem that I am trying to address in the Unity Editor.

**Comment by SirIntruder** [comment]
You are definatelly right, open c# project is the problem. Just be aware that once you get vscode into this bugged state, opening scripts through project window will get bugged as well

**Comment by miniwolf** [comment]
I see :) So this is a problem within Unity, and not part of this project. I have a bunch of changes within Unity related to how opening c# files are dealt with, and how VS Code is dealt with in general. These changes will be rolled out at some point. It is a bigger process to get that in, but I will put this on the list of changes that needs to happen as well.

**Comment by miniwolf** [comment]
Closed as fix has landed in Unity. If anyone keeps experiencing this problem, you may need to upgrade to a newer version of Unity.
