### ISSUE TITLE
Attach and immediate Detachment.

### ISSUE THREAD

**Issue by crysyn** [Unity-Technologies/vscode-unity-debug#89]
## Expected Behavior
When attaching to unity I expect the debugger to stay attached until I disconnect it.

## Current Behavior
Instead of staying attached the debugger disconnects with a few seconds.

## Steps to Reproduce (for bugs)
1. Install Unity
2. Install VSCode (Does not seem to matter between insiders or normal build)
3. Run Unity and load a project
4. Select 'Unity Editor' as the launch configuration and click play.

## Context
I am just trying to debug upgrading a unity project to 2018.1 and the .NET 4.0 environment. I was seeing this same response with the current release version of the unity debugger extension and thought upgrading it would help since it was targeted at supporting the new .NET. I am still however seeing the issue as is. With no one else reporting this I am just wondering if I have something out of date or some other expectation that I simply do not have. I am just out of ideas of what to look for.

## Your Environment
* Unity Version: 2018.1.2f1
* VS Code Version: 1.24-Insider
* Version of the debugger tool: 2.6.0
* Operating System and version: macOS High Serria 10.13.4

## Debugger Log
15:39:39.425492: Log
---

15:39:39.445140: UnityDebug
15:39:41.313946: Found Unity process: Unity Editor (Unity) (43350)

**Comment by miniwolf** [comment]
I have seen this issue occurring with a user having a very old version of mono installed. Could you check which version you have? 5 and above is recommended.

**Comment by crysyn** [comment]
I am running 5.9.6 but when I load it it does say it is not optimized and needs to be updated.

**Comment by miniwolf** [comment]
I see that 5.12.0 is the newest stable. But still, I am a bit surprised if that would resolve your issue.

**Comment by crysyn** [comment]
When I go to MonoDevelop it tells me to download Visual Studio for Mac... Is there a specific place I can go to get 5.12.0?

**Comment by miniwolf** [comment]
You can get it from this website: https://www.mono-project.com/download/stable/#download-mac

**Comment by crysyn** [comment]
That does not seem to have resolved the immediate disconnect issue... Though loading MonoDevelop via Finder still seems to load the older Unity specific version.

**Comment by crysyn** [comment]
I resolved the issue: My Unity VSCode plugin was out of date. I disabled the plugin, updated it and then re-enabled it and now VSCode 2.6.0 is attaching and holding it's attachment.

**Comment by miniwolf** [comment]
Interesting. :D you did say that your vs code debugger was 2.6.0 so I assumed that was true :)

**Comment by crysyn** [comment]
I had downloaded the debugger from the forum post about it supporting the newer .net environments, hehe.
