### ISSUE TITLE
Multiple Targets Found Error Connecting Debugger in Ubuntu

### ISSUE THREAD

**Issue by K0j0** [Unity-Technologies/vscode-unity-debug#9]
So the problem here is that if you try to run the debugger it fails with the error
`"Multiple targets with the name 'Unity Editor' running. Unable to connect."`

The reason for this is because the logic that attaches Unity (game engine) processes also includes Unity (UI) processes in Ubuntu. In Ubuntu the UI is known as Unity and has been this way for several years. When UnityProcessDiscovery.GetEditorProcesses() runs in MonoDevelop.Debugger.Soft.Unity it also includes UI processes such as unity-files-daemon and unity-scope-home.

A workaround I added was to add a check which would exclude processes with a hyphen in their names since all of the Unity UI processes seem to have those. I updated UnityProcessDiscovery.GetEditorProcesses() at about like 146 to be this:
```csharp
if(!p.ProcessName.Contains("-")){ // Exclude UI processes. Not a very good check
    unityEditorProcesses.Add (new UnityProcessInfo (p.Id, string.Format ("{0} ({1})", "Unity Editor", p.ProcessName)));
}
```

I was going to add this as an issue in the MonoDevelop.Debugger.Soft.Unity repo but I didn't see an option to do that in its repo for some reason.

Anyways, this should probably get fixed in that UnityProcessDiscovery function. It could be handled later by the extension in UnityDebugSession.Attach(). That function could filter the the list it gets for hyphens, but the source of the problem is that GetUnityEditorProcesses() function. Maybe you could rename the process "Unity3D" on Ubuntu? Or maybe you could get the process id for the editor earlier somehow and do a comparison against it? Also, the UI process in Ubuntu seem to be all lowercase where the the game engine process starts with a capital U. Idk, just brainstorming.

Whew, I'm tired! Sorry to ramble on. Hope this is helpful and gets fixed so others don't get stuck like I did :-)

**Comment by lukaszunity** [comment]
Hey, 

Thanks for reporting this issue. What is the exact name of the Ubuntu UI Unity process? `-unity`

**Comment by K0j0** [comment]
There are several. Here's my debug log for the extension when I use the one provided.

`00:27:24.108331: Found Unity process: Unity Editor (unity-settings-daemon) (1933)
00:27:24.108574: Found Unity process: Unity Editor (unity-panel-service) (1962)
00:27:24.109321: Found Unity process: Unity Editor (unity-fallback-mount-helper) (2204)
00:27:24.109938: Found Unity process: Unity Editor (unity-scope-home) (14957)
00:27:24.110560: Found Unity process: Unity Editor (unity-scope-loader) (14978)
00:27:24.111184: Found Unity process: Unity Editor (unity-files-daemon) (14979)
00:27:24.111839: Found Unity process: Unity Editor (unity-music-daemon) (15159)
00:27:24.112465: Found Unity process: Unity Editor (Unity) (15362)`

The last process (15362) is the actual Unity3D Editor. The rest are UI processes. I don't know whether or not this is a comprehensive list either. There could be other unity UI processes. They all seem to have hyphens though.

**Comment by lukaszunity** [comment]
Thanks. I will filter out any processes that start with `unity-`.

**Comment by lukaszunity** [comment]
Should be fixed in 2c811e4950ef85e12db9132ccb1ab5cb6395c22c

**Comment by K0j0** [comment]
Yeah, this looks good. I actually ran into another issue with this though. I got the multiple targets error again and checked the logs. Both processes were Unity. I ran a `ps aux | grep unity` and saw that there were actually 2 Unity processes running. One was [defunct](http://askubuntu.com/questions/201303/what-is-defunct-for-a-process-and-why-it-doesnt-get-killed) though. 

I think that may have happened because I was opening an existing project for the first time and it took a little while to import the assets. Only a guess. Anyways, the debugger wouldn't attach. I played around with the find process logic a bit to see if I could filter out defunct processes. "Defunct" does not appear in the process name though and the HasExited value was not set to true.

Closing Unity and restarting it fixed the issue though. If there isn't a way to filter out defunct processes maybe it should just be mentioned to Linux Users that they should try restarting Unity if they run into this. They could also manually kill the defunct process.

![unitydefunct](https://cloud.githubusercontent.com/assets/2118306/13477813/ff81ab2e-e082-11e5-990d-1363108092d8.png)

**Comment by lukaszunity** [comment]
Thanks for the info. I also experience this issue sometimes on OSX and Windows where Unity does not shut down properly and I end up with "Not responding" processes.

I've now added logging of the processes that are found in this case, hopefully that will make it clear that you have multiple Unity processes running. https://github.com/Unity-Technologies/vscode-unity-debug/commit/64fae2a4788d1ffafe103c073de24bc8b676b5fa

**Comment by Rombersoft** [comment]
I have this problem too in version 2018.2. Have not you really fixed this problem yet? Oh my God!

```
destructor@Toshiba-Satellite-C660:~$ ps ax | grep Unity
 1378 pts/0    S+     0:00 grep --color=auto Unity
 6595 ?        Sl     0:50 evince file:///media/destructor/Documents/%D0%91%D1%96%D0%B1%D0%BB%D1%96%D0%BE%D1%82%D0%B5%D0%BA%D0%B0%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%96%D1%81%D1%82%D0%B0/Unity/Unity%20%D0%B2%20%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B8.pdf
18466 ?        Sl     0:16 evince file:///media/destructor/Documents/%D0%91%D1%96%D0%B1%D0%BB%D1%96%D0%BE%D1%82%D0%B5%D0%BA%D0%B0%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%96%D1%81%D1%82%D0%B0/Unity/Unity%20-%20%D1%81%D0%B0%D0%BC%D0%BE%D1%83%D1%87%D0%B8%D1%82%D0%B5%D0%BB%D1%8C.pdf
31724 ?        Ssl    2:27 ./Unity
31749 ?        S      0:00 /opt/Unity/Editor/UnityHelper --type=zygote --no-sandbox --lang=en --log-severity=disable --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36 Unity/2018.1.0f2 (unity3d.com;light)
31939 ?        Sl     0:00 UnityShaderCompiler /opt/Unity/Editor/Data ./Library/shadercompiler-UnityShaderCompiler0.log 34680 /opt/Unity/Editor/Data/PlaybackEngines
32138 ?        Z      0:00 [Unity] <defunct>
32153 ?        Z      0:00 [Unity] <defunct>
```

**Comment by miniwolf** [comment]
@rombersoft take a look a the preview release mentioned here https://github.com/Unity-Technologies/vscode-unity-debug/issues/43

**Comment by Rombersoft** [comment]
Why? Problem hasn't resolved yet!

**Comment by Rombersoft** [comment]
Moreover Unity Editor crushes on Ubuntu 16.04 when I am moved across working desktops. When I am returning to the working desktop where was started Unity Editor it becames by gray background and after 1 minute crashes. Really during for a few years developing its for Linux did not make it much better. I don't know how can pay for this not done product.

**Comment by miniwolf** [comment]
@Rombersoft yes it has been resolved. The newest preview release has resolved this issue.
However if you are having some additional issues when using the newest 2.5.0 release then I would be happy to help you.
