### ISSUE TITLE
Unable to hook on .Net 4.x (Linux)

### ISSUE THREAD

**Issue by Eyap53** [Unity-Technologies/vscode-unity-debug#94]
Hi all ! Thanks in advance for taking time to help me.

## Context

I added a module to my project that needed an earlier version of C#, so i upgraded the runtime .Net 4.x. But since then, I can't hook my unity with VSCode (omnisharp is telling me that it is attached to unity, but breakpoints are not working).
I'm pretty sure I miss some dependency, but I also believe I got the latest updates... I am stuck for a few days now, that's why I decided to ask for help here. (I'm really sorry if this is really a dependency problem)

## Expected Behavior
Unity hook on runtime .NET 4.x

## Current Behavior
Tested with a new empty project : 
Unity hook on 3.5 (breakpoints are working). 
Switching to 4.x wihtout changing anything else, it's not working anymore.

## Steps to Reproduce (for bugs)
1. Create Empty project with a basic monobehaviour.
2. Add some breakpoints
3. Try hooking with .NET 3.5 -> Works
4. Switching to 4.x
5. Try hooking -> Doesn't work

## Your Environment
* Unity Version: 2018.2.0b7
* VS Code Version: 1.24.1
* Version of the debugger tool: 1.3.0
* Operating System and version: Ubuntu 18.04
* .NET Core SDKs installed:  2.1.301
* .NET Core runtimes installed:  2.1.1

**Comment by bsymon** [comment]
I have the same issue on Windows.

**Comment by miniwolf** [comment]
Hey there is a preview release out that you can use to work under the new 4.x runtime, check it out here: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/

**Comment by Eyap53** [comment]
Thanks for you reply !
I just tried this on windows, and it seems great 😄 ! (It solved the same problem i had on another project). I will try that on my laptop this evening, and update this comment.

**Comment by bsymon** [comment]
Works great ! Thank you :)
