### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by seeyou1984** [Unity-Technologies/vscode-unity-debug#95]
UnityDebug: Initializing
UnityDebug: Searching for Unity process 'Unity Editor'
UnityDebug: Multiple targets with name 'Unity Editor' running. Unable to connect
UnityDebug: Found Unity process 'Unity Editor (Unity)' (19952)
UnityDebug: Found Unity process 'Unity Editor (Unity)' (25632)
UnityDebug: Found Unity process 'Unity Editor (Unity)' (26092)

**Comment by miniwolf** [comment]
Which version of the Unity Debugger are you using?
