### ISSUE TITLE
Watch view,  Cannot view the properties of a variable

### ISSUE THREAD

**Issue by fjqingyou** [Unity-Technologies/vscode-unity-debug#97]
Hello!
VSCode 1.24.1
Debugger for Unity 2.6.0
Mono Debug 0.15.8
OS : macOS Sierra 10.12.6

Sorry, My English is very bad, so , I'm upload a screenshots.

![wx20180629-103255](https://user-images.githubusercontent.com/31087168/42070283-3a5e8922-7b88-11e8-9bbb-b13aa0f44ada.png)

rectTopStack get success, it's a System.Collections.Generic.Stack<T> instance, it have a Count property, but , I using it property to watch view,  Evaluate request failed(invalid expression)

**Comment by sterling000** [comment]
I also have the same issue with a fresh install.

**VS Code info:**

Version: 1.25.0
Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
Date: 2018-07-05T13:11:58.697Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

**Debugger for Unity Version 1.3.0**

**Comment by miniwolf** [comment]
@sterling000 I would recommend that you update to the newest preview version to eleminate as many issues as possible. You can always find the latest preview version from this version: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/

**Comment by miniwolf** [comment]
@fjqingyou Do you have a small sample project that I could try out?

**Comment by fjqingyou** [comment]
@miniwolf 
hello, this issues disappearing!

i'm compare Environmental
VSCode 1.25.0 (auto update)
Debugger for Unity 2.6.2 (auto update too)
Mono Debug  -----not change
OS : macOS Sierra   -----not change

I'm need close this issues?

**Comment by miniwolf** [comment]
Well if this appears again, you can always reopen the issue or create a new one :)
