### ISSUE TITLE
Attach Multiple targets

### ISSUE THREAD

**Issue by yuchting** [Unity-Technologies/vscode-unity-debug#98]
Hi great unity dev:

When I installed and configured debugger plugins for VSC, and found it had been support multi targets in its release note, but actually, I failed.

Look:
![image](https://user-images.githubusercontent.com/1817716/42308997-fd287c52-8069-11e8-85cd-c298a6cb7079.png)

When I selected any item of these:

![image](https://user-images.githubusercontent.com/1817716/42309006-02a029e6-806a-11e8-9549-33c006f111d7.png)

Windows 10 least version
VS Code version: 1.24.1
plugins version: 1.3.0
Unity version: 5.4.5p5

I searched a similar [issue](https://github.com/Unity-Technologies/vscode-unity-debug/issues/65) which was marked closed, but I think it's useless for me.

I use VS 2017 and unity debugger now, it is simple and good:
![image](https://user-images.githubusercontent.com/1817716/42309431-232f3660-806b-11e8-910b-5467d77313b0.png)

Could someone help me? 
Thanks!

**Comment by miniwolf** [comment]
I believe you are having the same issue as https://github.com/Unity-Technologies/vscode-unity-debug/issues/96 so I will close this as duplicate if you believe this is not the case, I can reopen it again.
