### ISSUE TITLE
Error Could not find target name 'Unity Editor'

### ISSUE THREAD

**Issue by tchrisbaker** [Unity-Technologies/vscode-unity-debug#99]
I get the following error when trying to debug 
https://imgur.com/a/bfJBBrT

My Unity Editor is running. I'm on Windows 10. 

In the Debug Console in VSCode it says 

UnityDebug: Initializing
UnityDebug: Searching for Unity process 'Unity Editor'
UnityDebug: Disconnected

**Comment by miniwolf** [comment]
What version of VS Code and the VS Code Unity Debugger are you using?

**Comment by tchrisbaker** [comment]
VSCode 1.25.0
Debugger 1.3.0

**Comment by tchrisbaker** [comment]
Unity Version is 2017.1.0f3

**Comment by miniwolf** [comment]
Could you try to upgrade to the preview release that is listed in this forum post: https://forum.unity.com/threads/unity-debugger-extension-for-visual-studio-code-2-0-x-preview-release.526263/
It may be able to resolve the issue.

**Comment by tchrisbaker** [comment]
Still having the same issue. It's version 2.6.3 now

**Comment by miniwolf** [comment]
Can you find the Unity Editor in your process list? It should be "Unity.exe" with a description "Unity Editor"

**Comment by tchrisbaker** [comment]
oops...sorry I had renamed my exe file to something other than unity.exe. That was the problem :)

**Comment by miniwolf** [comment]
:D There we go.
Sometimes we have to dig a little deeper. Glad we got it working :)

**Comment by tchrisbaker** [comment]
Yes thank you for your help. You asking me about unity.exe reminded me
